### ISSUE TITLE
Allow Website config, and use it when subscribing a website bound customer

### ISSUE THREAD

**Issue by jaredkipe** [ebizmarts/magemonkey#103]
Right now, the API and Helpers use the current store to get the configuration (and a somewhat odd way to do it during configuration since it is technically admin scope).
If you have more than one website, you have the choice to scope a customer to a specific website (not store).  This is a logical segregation of customer accounts and is used extensively in the industry.

The problem is that if an admin creates the account or modifies it's 'subscription' settings (subscribe/unsubscribe) the customer will ALWAYS be signed up using the default config.

Likewise the customers 'MailChimp List Activity' will be pulled from the default config (assuming they have history on the default config list).

I started working on a patch for this and quickly realized that the level of refactoring that would need to happen would make the patch unmaintainable, and unlikely that a pull request would be accepted to support the behavior.

Please consider pulling the website, from the customer, and injecting the scope from the admin page into the API/Helpers (as opposed to the way they work now by 'figuring' out the config scope by query parameters).
Thank you!

**Comment by gonzaloebiz** [comment]
Will be considered in the MageMonkey integration for Magento2
