### ISSUE TITLE
Please change config.xml due to 404 on "send to mailchimp" action

### ISSUE THREAD

**Issue by jh1987** [ebizmarts/magemonkey#105]
Due to Patch 5994, the config.xml for the adminsection needs to be changed:

`<admin>
        <routers>
            <monkey>
                <use>admin</use>
                <args>
                    <module>Ebizmarts_MageMonkey</module>
                    <frontName>monkey</frontName>
                </args>
            </monkey>
        </routers>
    </admin>`

Otherwise a 404 will be thrown

**Comment by Santiagoebizmarts** [comment]
@jh1987 Where do you get the 404 error? It works okay for me. Please make sure you have the latest version of MageMonkey installed.

**Comment by jh1987** [comment]
I have the latest version, ending with .35 but if you have the installed the the 5994 Patch installed, the "manual" send to mailchimp in the order grid is throwing a 404.

My config.xml admin node looks like this `   <admin>
        <routers>
             <adminhtml>
                <args>
                    <modules>
                        <monkey before="Mage_Adminhtml">Ebizmarts_MageMonkey_Adminhtml</monkey>
                    </modules>
                </args>
            </adminhtml>
            <monkey>
                <use>admin</use>
                <args>
                    <module>Ebizmarts_MageMonkey</module>
                    <frontName>monkey</frontName>
                </args>
            </monkey>
        </routers>
    </admin>`

I also have an js error, caused in the emailcatcher.phtml because the linkes 48-55 are not correctly commented out.

**Comment by gonzaloebiz** [comment]
@jh1987 thanks for your feedback
Please see at https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/etc/config.xml#L180-L190
As you see, the xml is OK, let us know if you find an issue with this

Best
