### ISSUE TITLE
Module uses template vars/blocks that are not whitelisted (SUPEE-6788)

### ISSUE THREAD

**Issue by erfanimani** [ebizmarts/magemonkey#106]
Also, the newest version seems to be 1.1.35 (from the Magento Connect page), but the latest release on Github seems to be 1.1.33. I'm not sure if I can just fork it and update from 1.1.35 (downloaded from Magento Connect) to our fork (forked from Github).

**Comment by erfanimani** [comment]
This is fixed now with the new version that's on Connect (1.2.0). It would be good if the Git tags would be updated according to the Magento Connect releases though.

**Comment by gonzaloebiz** [comment]
See version 1.2.1

**Comment by erfanimani** [comment]
Thanks @gonzaloebiz
