### ISSUE TITLE
Error getTable if does not exists

### ISSUE THREAD

**Issue by LoftyDeploy** [ebizmarts/magemonkey#107]
If you are on magento < 1.9.2.2 and want to update ebizmarkts, I believe ```getTable``` will raise error if does not exists: https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/AbandonedCart/sql/ebizmarts_abandonedcart_setup/mysql4-upgrade-1.1.35-1.2.0.php#L15

R

**Comment by avra911** [comment]
The error is: ```Can't retrieve entity config: admin/permission_block```

**Comment by Santiagoebizmarts** [comment]
This is solved in our current version 1.2.1 https://github.com/ebizmarts/magemonkey/blob/1.2.1/app/code/community/Ebizmarts/AbandonedCart/sql/ebizmarts_abandonedcart_setup/mysql4-upgrade-1.1.35-1.2.0.php#L16
