### ISSUE TITLE
Review items.phtml word missing translation

### ISSUE THREAD

**Issue by avra911** [ebizmarts/magemonkey#108]
Hi,

I found a missing translation in review email template:

https://github.com/ebizmarts/magemonkey/blob/master/app/design/frontend/base/default/template/ebizmarts/autoresponder/review/items.phtml#L38

It looks like: ```Rate``` is missing ```$this->__()``` and probably needs to be added as well in locale.

Best,
Razvan

**Comment by avra911** [comment]
see: https://github.com/ebizmarts/magemonkey/pull/109

**Comment by Santiagoebizmarts** [comment]
@avra911 Thanks for this. I will check the PR to check the other fixes.
