### ISSUE TITLE
Configscope store param request.

### ISSUE THREAD

**Issue by JamesAnelay** [ebizmarts/magemonkey#111]
Hi,
I had a conflict with an extension today with a extension that is a storefinder extension that sets a "store" parameter as below:

```
$request->setModuleName('storelocator')
            ->setControllerName('index')
            ->setActionName('store')
            ->setParam('store', $storeKey);
```

In Ebizmarts_MageMonkey_Helper_Data the below code is called a couple of times. If i've set the "store" as the name of my physical store e.g in my case "cambridge" which isn't a Magento store I get a 404.

It's easy enough to fix by commenting out the below line fixing my 404 page issue but i'm just curious to know the use case?
// $configscope = Mage::app()->getRequest()->getParam('store');

It also seems this code is only run when "Enable Ecommerce360 for" is set to cron. Which as you can imagine setting this can then a day or two later having my storefinder pages start 404ing was a debugging headache.

But yeah just looking to know when and how the "configscope" is used and mabey if it would be better to use the magento default ?___store param and even then if its possible to check if the store exists before using it to grab config values.

Thanks in advance - James

P.S thanks for the great free extensions :)

**Comment by Santiagoebizmarts** [comment]
Hello @JamesAnelay,

Thanks for your feedback. That code is used when certain configuration is saved in a particular store view. It checks the current scope to actually save everything associated to the store view it was saved on.

Can you elaborate on how you found this conflict? Did something failed? Any error message displayed?

Regards.

**Comment by JamesAnelay** [comment]
Hi,

So I found the conflict because all my physical store location for the storefinder on our website e.g http://www.revital.co.uk/storelocator/chelsea/ return a Magento error page. I'm afraid the error has been lost now.

But these pages set a store param using the $storeKey which in the above case would be "chelsea" as per below:

```
$request->setModuleName('storelocator')
            ->setControllerName('index')
            ->setActionName('store')
            ->setParam('store', $storeKey);
```

Once this is set it mean that return Mage::getStoreConfig("monkey/general/$value", $store); becomes:

return Mage::getStoreConfig("monkey/general/chealsea", $store); which isn't a valid item which causes the error.

Magento has the ___store I am guessing that the ___ is there to avoid these sorts conflicts? So mabey it makes sense to use that instead. That said I don't know for certain thats why it has the three underscores just guessing.
