### ISSUE TITLE
Synchronisation of Ecommerce360 

### ISSUE THREAD

**Issue by devillep** [ebizmarts/magemonkey#112]
Hi, 

I've setup Ecommerce360 on a website which has been running for a couple of years. I have synchronised my orders. Having checked some of the totals I can see that the number of orders between Magento and MailChimp don't match.

Looking in the log files and at the data that is missing it appears that orders where products have been deleted are not sent to MailChimp.

This is an example of the data for an order that hasn't been sent. Obviously not all of this information is available now the product has been deleted, but would it be possible to populate it with information from the order_item table, rather than the product table?

```PHP
2016-01-04T10:45:01+00:00 DEBUG (7): Array
(
    [0] => Array
        (
            [id] => 100004656
            [total] => 120.8300
            [shipping] => 5.0000
            [tax] => 24.1700
            [store_id] => 1
            [store_name] => XXX
            [order_date] => 2013-07-11 16:05:14
            [plugin_id] => 1215
            [items] => Array
                (
                    [0] => Array
                        (
                            [product_id] => 
                            [sku] => 
                            [product_name] => [size:No|brand:No|colour:No|shirt_size:No|]
                            [category_id] => 0
                            [category_name] => None
                            [qty] => 1.0000
                            [cost] => 120.8300
                        )

                    [1] => Array
                        (
                            [product_id] => 
                            [sku] => 
                            [product_name] => [size:No|brand:No|colour:No|shirt_size:No|]
                            [category_id] => 0
                            [category_name] => None
                            [qty] => 1.0000
                            [cost] => 0.0000
                        )

                )

            [email] => XXXX
    	)

    [__pid] => 12255
)
```

Could you please confirm that what I'm seeing is correct and whether there is a solution for this?

Thanks
Paul

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for this feedback.
How are you sending this? Is it manual export of the orders? Because if you have your cron jobs working properly it should save the information as soon as the order is made.

Regards.

**Comment by devillep** [comment]
Hi,

Yes, crons are running and new orders are exported correctly. The problem is with manually exporting historical order data, specifically where products have been deleted.

Just wanted to know whether it was possible to get the missing product_id and sku from sales_flat_order_item if the product no longer exists?

Thanks

**Comment by centerax** [comment]
Thats a good idea @devillep , we will take a look at that approach and get back to you with an answer shortly.

**Comment by MikeParkin** [comment]
@centerax Thanks - will be good to get this one resolved!

**Comment by nbrewer** [comment]
This is happening to us too. It looks like the latest version of the extension has commented out the saveCookie code that used to save campaign data.

**Comment by devillep** [comment]
Thanks for that. Do you have an ETA on the next release, and will it contain this commit?

**Comment by centerax** [comment]
It will contain this commit.

ETA is end of February.

**Comment by MikeParkin** [comment]
@centerax thank you.

**Comment by MikeParkin** [comment]
Hi @centerax - is this now resolved?

**Comment by Santiagoebizmarts** [comment]
Yes, this is already in our current version.

Regards.
