### ISSUE TITLE
Mail Group Functionality seems to be broken

### ISSUE THREAD

**Issue by devillep** [ebizmarts/magemonkey#113]
Hi there,

We are investigating to understand how the "group" functionality works within lists. 

Our scenario is that when a customer creates a customer account, we would like them to be added to a list in MailChimp (which works) and assigned a selected group (not working).

The issue appears to be that we do not want customers to select this group themselves, it should be default. There is an option available for this within the configuration and the documents refer to the option as if it will do as desired:

![screen shot 2016-01-06 at 12 44 13](https://cloud.githubusercontent.com/assets/16557144/12142860/44daa0b8-b473-11e5-8980-495660d37849.png)
![screen shot 2016-01-06 at 12 44 25](https://cloud.githubusercontent.com/assets/16557144/12142864/4917140e-b473-11e5-9fec-337036a94750.png)

There are two issues with this, having traced through the code, the ONLY place that "setListGroups" is called (which is required to save the customer group) is within Ebizmarts_MageMonkey_Helper_Data::handlePost. This handlePost method is only called from within Ebizmarts_MageMonkey_SignupController::saveadditionalAction method and it only contains the groupings if the information is POSTed.

```php
// Taken from POST data
$groupings = $lists[$listId];
unset($groupings['subscribed']);

// Get the remote groups from MailChimp and set to empty array if not existing
$customerLists = $api->listMemberInfo($listId, $email);
$customerLists = isset($customerLists['data'][0]['merges']['GROUPINGS']) ? $customerLists['data'][0]['merges']['GROUPINGS'] : array();

foreach ($customerLists as $clkey => $cl) {
    if (!isset($groupings[$cl['id']])) {
        $groupings[$cl['id']][] = '';
    }
}

// Set the groups
$customer->setMcListId($listId);
$customer->setListGroups($groupings);
```

As far as I can see, the default groups are never used during normal operation, so the group is never sent to MailChimp.

Issues that we're facing:

* We cannot see how the default groups are ever sent to MailChimp
* There does not appear to be any functionality for the group to be sent during a bulk action - so we cannot go back and change customer groups and resync them

Thanks
Paul

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for this feedback and sorry for the delay.
You can see the logic at https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Helper/Data.php#L665-L742

Sending the groups under the GROUPINGS merge tag adds the subscriber to the groups properly.
On the last matter you mention about the export, you are right. I'll be fixing this and updating this ticket.

Regards.

**Comment by pocallaghan** [comment]
@Santiagoebizmarts the method `Ebizmarts_MageMonkey_Helper_Data::_checkGrouping` appears to not do anything when registering a new customer `&& !$customerCreateAccountSubscription`. Surely a customer being registered is when you would expect the default group to be set?
