### ISSUE TITLE
Lost Backward compatibility with Magento 1.5

### ISSUE THREAD

**Issue by gido** [ebizmarts/magemonkey#114]
It looks like from version 1.2.1 of this module, we lost the backward compatibility with old version of magento by the use of `Varien_Db_Adapter_Pdo_Mysql::isTableExists()` introduced in Magento 1.6 (not sure).

https://github.com/ebizmarts/magemonkey/blob/1.2.1/app/code/community/Ebizmarts/AbandonedCart/sql/ebizmarts_abandonedcart_setup/mysql4-upgrade-1.1.35-1.2.0.php#L16

I think this is related to #107 

I got the following fatal error:

```
Fatal error: Call to undefined method Varien_Db_Adapter_Pdo_Mysql::isTableExists()
in /path/to/magento/app/code/community/Ebizmarts/AbandonedCart/sql/ebizmarts_abandonedcart_setup/mysql4-upgrade-1.1.35-1.2.0.php on line 16
```

I think is OK to drop the support to older magento release but in this case it would be nice to inform and bump the project with at least a minor version.

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for helping us noticing this. We'll see if there is a way to do this compatible with prior versions of Magento.
