### ISSUE TITLE
Schedule for 2nd abandoned cart email will always be 1 day early

### ISSUE THREAD

**Issue by maderlock** [ebizmarts/magemonkey#120]
In src/app/code/community/Ebizmarts/AbandonedCart/Model/Cron.php method _processRun($adapter, $run, $storeId) the special case for the second email ($run == 1) when the first email is set to a number of hours, tries to get the difference between the first email and the second by subtracting a fraction of a day. The issue with this is that the formatting method _getIntervalUnitSql($interval, $unit) then outputs this difference as an integer.

e.g. If the first email is set to 1 hour and the second to 1 day:
* $diff will be set to 1
* $diff will then be reduced by 1/24 to 0.959
* $expr will end up as DATE_SUB('2016-02-03 14:34:32', 'INTERVAL 0 DAY')

**Comment by maderlock** [comment]
The solution to this is to convert the second email to always use hours:

>        $diff = $this->days[$run];
>        if ($run == 1 && $this->unit == Ebizmarts_AbandonedCart_Model_Config::IN_HOURS) {
>            $diff = $diff * 24 - $this->days[0];
>        } elseif ($run != 0) {
>            $diff -= $this->days[$run - 1];
>        }
>
>        // set the top date of the carts to get
>        $expr = sprintf('DATE_SUB(%s, %s)', $adapter->quote(now()), $this->_getIntervalUnitSql($diff, 'DAY'));
>        if ($run <= 1 && $this->unit == Ebizmarts_AbandonedCart_Model_Config::IN_HOURS) {
>            $expr = sprintf('DATE_SUB(%s, %s)', $adapter->quote(now()), $this->_getIntervalUnitSql($diff, 'HOUR'));
>        }

**Comment by Santiagoebizmarts** [comment]
After a bit of investigation I found myself wondering why was this working so far. The reason is at https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/AbandonedCart/Model/Cron.php#L202-L210.
I guess it would be better to filter this in the SQL query so it will be changed but the email will not go early, it will go when it should.

Kind Regards.

**Comment by maderlock** [comment]
Thanks. While completely non-intuitive I see now why this was working. It turned out to be a local issue that was stopping my emails from being sent at the right time.
