### ISSUE TITLE
"Send product to a friend" emails are now getting blocked by the new Mandrill

### ISSUE THREAD

**Issue by bigware** [ebizmarts/magemonkey#122]
Since "Send product to a friend" emails use the email address of the person sending the item to their friend, Mandrill is now blocking those email because the sending domain is not verified.

**Comment by Santiagoebizmarts** [comment]
Hello,

We know about this issue and have added this in our roadmap and will be ready as soon as possible.

**Comment by bigware** [comment]
Great. I turned off the "Send product to a friend" feature for now.

**Comment by Santiagoebizmarts** [comment]
This have been fixed in the commit above. A new version will be released this week.
