### ISSUE TITLE
Abandoned cart issue

### ISSUE THREAD

**Issue by etsanov** [ebizmarts/magemonkey#123]
I wrote a reply to an old ticket; however, I am not sure if it will be read, so I also post this issue here. I hope I am not overdramatic ^_^.

I tested things, and here's what happens:

I am a customer with email example@example.com. I have an account on SITE1 and SITE2 websites, both part of one Magento installation.

I go ahead and add something to my cart on SITE1, and I abandon the cart. Then I update the values in the database so that I get an email with coupon (automatically generated one). The coupon is properly generated for SITE1 under Promotions->Shopping cart price rules, and I get an email with the coupon. Everything is okay so far. I can use the coupon on SITE1.

Now I log in with example@example.com (the same email address) on SITE2. This is a separate website, and I am a separate customer. I add something to my cart on SITE2, and I abandon the cart. I update the values in the database and I get an email. However, the email is WITH THE SAME COUPON CODE that was generated for SITE1, and an actual coupon for SITE2 WAS NOT generated. So when I try to apply the coupon on SITE2, I get "Invalid coupon".

That does seem like a bug. I guess that I could use pre-generated coupons for now until the issue is solved, but I really prefer to use generated coupons.

I appreciate your dedication and expertise. Thank you for a great extension that makes Magento, MailChimp, and Mandrill work together nicely.

Please check this bug and let me know if it can be fixed within a timely manner.

If you have any questions, let me know.

Thank you again.

Best regards,
Emiliyan

**Comment by gonzaloebiz** [comment]
Hi @etsanov 

this issue was fixed on this commit https://github.com/ebizmarts/magemonkey/commit/31d72c9ea109d41450dbad0fe05530d3d0a15859

Best
