### ISSUE TITLE
Handle Subscriber issue

### ISSUE THREAD

**Issue by mkutyba** [ebizmarts/magemonkey#124]
Hello,

I have the following settings in Magemonkey Mailchimp section:
**Use Magento's confirmation email: Yes**
**Double opt-in** = System->Configuration->Customers->Newsletter->Subscription Options->Need to Confirm: **Yes**
The **list is set** in General Subscription option.

There is an event observer `Ebizmarts_MageMonkey_Model_Observer::handleSubscriber` for the `newsletter_subscriber_save_before`, but it doesn't write my email into table `monkey/asyncsubscribers` because of this line https://github.com/ebizmarts/magemonkey/blob/ed28e57963a6b213da801284123901f0d063c1ce/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L43
**The condition is true, so the method returns and doesn't execute further lines**, where it is this line
`Mage::helper('monkey')->subscribeToList($subscriber, $saveOnDb);`

This mentioned `if` is following:
`Mage::getStoreConfig(Mage_Newsletter_Model_Subscriber::XML_PATH_CONFIRMATION_FLAG, $subscriber->getStoreId())` = 1
&&
`Mage::getStoreConfig(Ebizmarts_MageMonkey_Model_Config::GENERAL_CONFIRMATION_EMAIL, $subscriber->getStoreId())` = 1
&&
`!Mage::getSingleton('customer/session')->isLoggedIn()` - I'm not logged in
&&
`Mage::app()->getRequest()->getActionName() != 'createpost'` - I'm not creating an account

So it evaluates to true and returns.

**Comment by Santiagoebizmarts** [comment]
This will be fixed in the version released today.
