### ISSUE TITLE
send custom emails from Magento through Mailchimp templates

### ISSUE THREAD

**Issue by deepu9** [ebizmarts/magemonkey#127]
Hi,
I'm building a custom module for my client. They asked for weekly emails using mailchimp templates. They've already set up the weekly templates in mailchimp. Now all I need is a function(s) from the magemonkey module to do the following tasks:

- Set the template for every subscriber

- Pass the template parameters into it & get the processed template

- Finally, send it through Mailchimp/Mandrill

Can you help me.

--
Regards
Sandeep

**Comment by centerax** [comment]
please post a question on http://ebizmarts.com/forums/view/1
