### ISSUE TITLE
Multi store setup not working

### ISSUE THREAD

**Issue by Arn2014** [ebizmarts/magemonkey#128]
Hi,

I am experiencing a configuration issue with my multi store setup, i have a main website with 3 store views , one for each language with different urls for each language.

i have seperate mailchimp accounts for each store view, so i can send newsletters in seperate langiages (all have their own api keys, and my malchimp groups are configured as visible..)

Problem:
During page load in my magento backend the
subscription (sub)group of my (German store view) is visible, But after the page has loaded
--- No data --- is displayed..seems like the code is losing the scope of the current store view..

(Btw: my standard store view (main website) scope displays the mailchimp subscription group correctly and also displays the correct values after the page has loaded

I am using magento CE 1.8.1 with all security patches and the latest magemonkey version 1.2.2.1

hope someone can help me further with this issue..

Thanks

best

A

**Comment by Santiagoebizmarts** [comment]
You can see the commit that solves this above. We will launch a new version this week with the changes.
