### ISSUE TITLE
Do Not Send Confirmation When Subscription Is Forced

### ISSUE THREAD

**Issue by sprankhub** [ebizmarts/magemonkey#129]
This is a follow-up on #101.

> I just updated the shop to the latest develop branch. This issue is not solved. The user still gets a confirmation mail if he did not explicitely check the subscribe box and was only forced to subscribe. And he is only added to the Mailchimp list if he clicks on the confirm button in the confirmation mail.

> If the user was forced to subscribe and did not check the subscribe box, he should not get any mail, but should be added to Mailchimp nevertheless. Could you please check that again?

**Comment by sprankhub** [comment]
@Santiagoebizmarts @centerax do you already know when you can have a look at this issue? This is quite an important topic imho.

**Comment by Santiagoebizmarts** [comment]
Hello,

Sorry for the delay, we have a lot in our plate right now.
This is a desired feature, please note this may be ilegal in some countries. You can set it to stop sending the opt-in confirmation email at https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/Model/MCAPI.php#L1647

Regards and sorry again for the delay.

**Comment by sprankhub** [comment]
Thanks for the feedback. I know that this may be illegal, but this is suspected behaviour:

- The admin configured that the user should be FORCED to subscribe.
- The user does NOT check the subscribe box.

Hence, the user should be subscribed "in the background" without any confirmation. If the admin does not want that, he must not enable "force subscription". I think this should be fixed in the extension.

**Comment by sprankhub** [comment]
Bump. I think this is still a major issue, which should be fixed.
