### ISSUE TITLE
Guest subscribtions don't work

### ISSUE THREAD

**Issue by Arn2014** [ebizmarts/magemonkey#130]
When a guest subscribes to the newsletter, with only an email address as input 
(No Firstname and Lastname value) the subscribers doesn't get added/synced with mailchimp, 
also not visible in export..

Magento 1.8.1 with all sequrity patches..

**Comment by Santiagoebizmarts** [comment]
Hello,

This is probably an error related to a required field on your MailChimp list or maybe the email address was already suscribed and deleted.
You can check the first possible cause on your MailChimp merge fields view, if the FNAME Merge field is required then uncheck the checkbox.
For the second one please check http://ebizmarts.com/forums/topics/view/21531

Regards.
