### ISSUE TITLE
You must specify a apikey value for the listBatchSubscribe method

### ISSUE THREAD

**Issue by johnnywidth** [ebizmarts/magemonkey#133]
I try call **listBatchSubscribe**, but i receive error

> You must specify a apikey value for the listBatchSubscribe method

My code:

`$api = new Ebizmarts_MageMonkey_Model_MCAPI(Mage::helper('monkey')->config("apikey"));`
`$listId = Mage::helper('monkey')->config('list');`
`$result = $api->listBatchSubscribe($listId, $batches, false, true, true);`

My **listId** and **apikey** is correct, i checked **apikey** by call `$api->ping()`, and it is OK

**Mailchimp API: v1.3**

**Comment by gonzaloebiz** [comment]
Hi @johnnywidth 

take a look at https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L266

Best

**Comment by johnnywidth** [comment]
@gonzaloebiz I used it before, but then decided use Ebizmarts_MageMonkey_Model_MCAPI like in api documentation. But it is still not working.

**Comment by gonzaloebiz** [comment]
Are you sure that $helperMonkey->getStoreByList($listId) returns a valid store?

**Comment by johnnywidth** [comment]
It return default store

**Comment by gonzaloebiz** [comment]
Put a Mage::log in https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/Model/MCAPI.php#L2509
to be sure if the apikey is ok

Best

**Comment by johnnywidth** [comment]
Yes, i made debugging all of calls stack. In this place i have api key.

**Comment by gonzaloebiz** [comment]
Try a Mage::log($post_vars) after this line https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/Model/MCAPI.php#L2520

**Comment by johnnywidth** [comment]
`Mage::log($params["apikey"], null, "test.log", true);`

This is a result (xxx - my api key, i cant show you them :))

> 2016-05-31T19:00:07+00:00 DEBUG (7): xxx

**Comment by gonzaloebiz** [comment]
Try a Mage::log($post_vars) after this line https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/Model/MCAPI.php#L2520

**Comment by johnnywidth** [comment]
It still here

> ...&double_optin=0&update_existing=1&replace_interests=1&apikey=xxx

**Comment by johnnywidth** [comment]
It was a problem with trying send a lot of data, i made chunked sending data and it is working good.
