### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by AydinHassan** [ebizmarts/magemonkey#134]
Hi, we are experiencing https://github.com/ebizmarts/magemonkey/commit/6ebede2fc0c09a9b8724c52e8e2b6ea18cba505a with latest tag.

Is it possible to tag a new release please?

**Comment by Santiagoebizmarts** [comment]
Hello,

We will create a new release this week.

Regards.

**Comment by sprankhub** [comment]
Bump

**Comment by alexcurtis** [comment]
Can we get a new release out asap please?

**Comment by centerax** [comment]
@Santiagoebizmarts please close this issue when the new version is released.
Thanks.

**Comment by alexcurtis** [comment]
@Santiagoebizmarts Thanks for the release. Would it be possible to get this into Magento Connect so its nice an easy to update via admin tool?

**Comment by centerax** [comment]
@alexcurtis We are working on it, MagentoConnect is crashing when we upload a new release.-
