### ISSUE TITLE
Background order creation process causes exception when updating customer.

### ISSUE THREAD

**Issue by jaredkipe** [ebizmarts/magemonkey#136]
I have a 'product subscription' extension that is used for making order on a recurring basis.  It operates on the cron and as such has no 'session'.

The observer for MageMonkey is not too particular about what exceptions it might cause, and thus causes them to leak out into the event itself.

```
Jun 13 10:00:17 coreos1 docker[86870]: [Mon Jun 13 10:00:17 2016] [hphp] [1:7f00c507b440:0:000001] [] exception 'Exception' with message 'No session id. Blocking rather than instantiate object early.' in /var/www/app/code/core/Mage/Newsletter/Model/Subscriber.php:363
Jun 13 10:00:17 coreos1 docker[86870]: Stack trace:
Jun 13 10:00:17 coreos1 docker[86870]: #0 /var/www/app/code/community/Ebizmarts/MageMonkey/Helper/Data.php(942): Mage_Newsletter_Model_Subscriber->subscribe()
Jun 13 10:00:17 coreos1 docker[86870]: #1 /var/www/app/code/community/Ebizmarts/MageMonkey/Helper/Data.php(905): Ebizmarts_MageMonkey_Helper_Data->subscribeToList()
Jun 13 10:00:17 coreos1 docker[86870]: #2 /var/www/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php(383): Ebizmarts_MageMonkey_Helper_Data->listsSubscription()
Jun 13 10:00:17 coreos1 docker[86870]: #3 /var/www/app/code/core/Mage/Core/Model/App.php(1358): Ebizmarts_MageMonkey_Model_Observer->updateCustomer()
Jun 13 10:00:17 coreos1 docker[86870]: #4 /var/www/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod()
Jun 13 10:00:17 coreos1 docker[86870]: #5 /var/www/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent()
Jun 13 10:00:17 coreos1 docker[86870]: #6 /var/www/app/code/core/Mage/Core/Model/Abstract.php(466): Mage::dispatchEvent()
Jun 13 10:00:17 coreos1 docker[86870]: #7 /var/www/app/code/core/Mage/Core/Model/Abstract.php(319): Mage_Core_Model_Abstract->_afterSave()
Jun 13 10:00:17 coreos1 docker[86870]: #8 /var/www/app/code/core/Mage/Core/Model/Resource/Transaction.php(151): Mage_Core_Model_Abstract->save()
Jun 13 10:00:17 coreos1 docker[86870]: #9 /var/www/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
...
```

The most obvious solution here is to simply wrap the bulk of the work in Observer::updateCustomer() with a try{} and just throw away the exception (allow the event stack to complete).

**Comment by Santiagoebizmarts** [comment]
Hello,

How do you update the customer? Can you give a bit more information on what the extension does?

Regards.

**Comment by jaredkipe** [comment]
I'm not updating a customer at all (specifically).  I'm just getting a 'sales/quote' model, building it up (adding items, customer, shipping/billing addresses), then getting a 'sales/service_quote' and passing it the quote to get back an order.  Then getting a 'sales/convert_order' model and giving it the order to finish it off.

This is all pretty standard, and to the best of my knowledge, the only way to properly build an order that calculates its own tax and bookkeeping for rewards points.

I don't believe there is anything explicit in the API that guarantees to observers that this process must have a session.  None of the stock Magento code seems to care about it.

My feeling is that if you don't want to be able to stop the event you're observing, you better make sure that you _cannot_ stop it.  (aka only do things that are safe, like modifying models you know about and own completely, or prepare to handle any errors that arise)

**Comment by jaredkipe** [comment]
I realize now my title is a bit of a red herring.  the 'updateCustomer' comes from Ebizmarts_MageMonkey_Model_Observer->updateCustomer()
but it is listening to the event 'customer_save_after' which must just be part of the 'order creation' process.

**Comment by Santiagoebizmarts** [comment]
Hello,

Sorry for the delay. The updateCustomer function should not be triggered on order creation. I just added a check for the back end customer creation on order creation.
Please see reference above.

Thanks for your feedback!
