### ISSUE TITLE
Unable to add to mailchimp newsletter subscribers

### ISSUE THREAD

**Issue by zhartaunik** [ebizmarts/magemonkey#137]
Ebizmarts_MageMonkey_Helper_Data::getMergeVars(...)

Existing code has few logical issues.
customer_id will allways exist, because $customer is not Customer object. It's Newsletter Subscriber object.
The other issue appeared at 13e80f1.
Can't understand the logic: If Customer has name - then take name from config. Else if name in config exist we take the name from customer. Which not exist if we moved here.

Patch attached
[magemonkey_newsletter_subscription_issue.txt](https://github.com/ebizmarts/magemonkey/files/323176/magemonkey_newsletter_subscription_issue.txt)

**Comment by madswexo** [comment]
@zhartaunik is correct in that the logic for guest FNAME and LNAME is reversed, and the config value is used if subscriber_firstname/lastname is set.

**Comment by driskell** [comment]
Hi @Santiagoebizmarts - do you need any more information on this issue in order to produce a fix? Would a pull request be accepted?

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for the feedback. I fixed the problem with the customer name being set improperly when the customer/subscriber has no name.
About the customer id, it will not return an id if the object is a subscriber because it calls the getCustomerId method.
