### ISSUE TITLE
Sweet Tooth points no longer work if need confirm is enabled

### ISSUE THREAD

**Issue by tomekjordan** [ebizmarts/magemonkey#139]
HI. Sweet Tooth points has quick fix to need confirm option in Mailcihmp's
app/code/community/Ebizmarts/MageMonkey/Model/Observer.php
they added:
`Mage::getModel('rewards/newsletter_subscription_observer')->initReward($subscriber);`
but its not working due your changes.
[http://help.sweettoothrewards.com/article/78-ebizmarts-magemonkey-mailchimp-extension](http://help.sweettoothrewards.com/article/78-ebizmarts-magemonkey-mailchimp-extension)

Where can I find quick fix for this? where need confirm function is now located in Mailchimp sources?

**Comment by Santiagoebizmarts** [comment]
@tomekjordan Hello and sorry for the delay.
What version of MageMonkey do you have installed? I don't think this is related to the need to confirm flag. Do you see the tags being send on your MageMonkey_ApiCall.log?

Regards.

**Comment by tomekjordan** [comment]
Hi. Sweet Tooth confirmed it as bug in their code, and they are working on fix. thanks
