### ISSUE TITLE
Fatal Error "Maximum function nesting level reached" in Checkout

### ISSUE THREAD

**Issue by sprankhub** [ebizmarts/magemonkey#140]
I get a fatal error when an existing customer orders again. The order is created in the backend, but the checkout success page is not shown due to the error.
I am using Magento 1.9.2.4 and Ebizmarts_MageMonkey 1.2.2.6.

`Fatal error: Maximum function nesting level of '250' reached, aborting!`

![image](https://cloud.githubusercontent.com/assets/930199/16911081/ba32cfe6-4cdc-11e6-8ba4-5a6e9a58ba49.png)

**Comment by gonzaloebiz** [comment]
Try with the 1.2.3 version please

**Comment by sprankhub** [comment]
@gonzaloebiz I just did, but the issue remains the same...!

**Comment by sprankhub** [comment]
@gonzaloebiz this is a critical issue. Could you please prioritise it?

**Comment by gonzaloebiz** [comment]
Please, specify he steps to reproduce it
Why you think that's a MageMonkey issue?

**Comment by sprankhub** [comment]
I sent you a complete callstack - this shows exactly what is happening. Actually you observe the event `newsletter_subscriber_save_before` and finally call `$subscriber->save()` again during your observer.

1. `Ebizmarts_MageMonkey_Model_Observer::handleSubscriber` (line 54) calls
2. `Ebizmarts_MageMonkey_Helper_Data::subscribeToList` (line 1000) calls
3. `Mage_Newsletter_Model_Subscriber::subscribe`, which dispatches the event `newsletter_subscriber_save_before` again, so (1) is called again.

In order to reproduce the issue, do the following:

1. Create a customer in the store and subscribe to the newsletter ("Sie sind momentan für das Abo "Allgemeines" eingetragen." = "You are currently subscribed to 'General Subscription"):
![image](https://cloud.githubusercontent.com/assets/930199/17247663/16a5709c-5595-11e6-8648-b7b6b9685427.png)

2. Put something in the cart.
3. Go through the checkout process. Last step will look similar to this:
![image](https://cloud.githubusercontent.com/assets/930199/17247722/8f2db146-5595-11e6-9a7d-67f2c9e14f58.png)
4. Click the buy button. The page will crash. If you have debug output enabled, you will see the error I posted in my first post (https://cloud.githubusercontent.com/assets/930199/16911081/ba32cfe6-4cdc-11e6-8ba4-5a6e9a58ba49.png).

There are "only" MageMonkey classes in the callstack, so I am pretty sure this is a MageMonkey issue.

**Comment by sprankhub** [comment]
Any news?

**Comment by centerax** [comment]
@sprankhub we could not replica so far. We will have another go today and let you know.

**Comment by gonzaloebiz** [comment]
Hi @sprankhub 

do you use a custom checkout? if yes, try with the default checkout.
If you have xdebug enabled, disable it or increase the max_nesting_level setting in xdebug configuration (you can do this with ini_set('xdebug.max_nesting_level', nnn))

Best

**Comment by centerax** [comment]
@sprankhub Whats your setting on **Subscribe On Checkout** ?

**Comment by gonzaloebiz** [comment]
@sprankhub 

thanks for your feedback see this https://github.com/ebizmarts/magemonkey/commit/c2dcc7fea2bc2a1794a10fed89c523e839e83603 to fix it.

In the next release will be available in the standard package

Best

**Comment by sprankhub** [comment]
Thank you. I can confirm that the commit fixes this issue. Since this issue is quite critical, it would be great if you released a bugfix version soon.
