### ISSUE TITLE
Popup when cookie is created, and Campaign no longer recognized when placing order.

### ISSUE THREAD

**Issue by bigware** [ebizmarts/magemonkey#143]
ebizmarts/magemonkey/campaignCatcher.js

Who's brilliant idea is it for my customers to **receive a popup** when they enter my website from a campaign email??
`
alert('creating cookie');`

Also, Magento no longer recognizes when an order comes from a campaign.
It seems like the whole commit messed quite a lot up.

**Comment by gonzaloebiz** [comment]
Update to the last version
