### ISSUE TITLE
JavaScript alert('creating cookie') left in distributed version 1.2.5

### ISSUE THREAD

**Issue by nawamedia** [ebizmarts/magemonkey#144]
In `js/ebizmarts/magemonkey/campaignCatcher.js` :24, someone forgot to remove a line from the development process.

`alert('creating cookie');` on line 24

You can recreate this bug when parameter name `mc_cid` or `mc_eid` exists in the URL GET Parameters.

You get one alert box per parameter.

**Comment by gonzaloebiz** [comment]
Closes this issue, is duplicated #143
