### ISSUE TITLE
Orders From Shopgate Are Not Sent to Mailchimp

### ISSUE THREAD

**Issue by sprankhub** [ebizmarts/magemonkey#145]
The [Shopgate Magento extension](https://www.magentocommerce.com/magento-connect/shopgate-the-leading-mobile-commerce-platform.html) imports Shopgate orders into Magento. These orders are not sent to Mailchimp. I think neither mail addresses nor order data is sent. Would it make sense for you to implement that? The Shopgate extension seems to dispatch some events like `checkout_submit_all_after` or `shopgate_add_order_after`, so it should be possible in a nice way.

**Comment by sprankhub** [comment]
Could you give me at least some official statement here? Thanks!

**Comment by Santiagoebizmarts** [comment]
Hello @sprankhub 
Sorry for the delay. We are not doing enhancements on MageMonkey. Our focus is with the new extension [MailChimp For Magento](https://connect.mailchimp.com/integrations/magento) atm.

Regards.

**Comment by alex-koepke** [comment]
@Santiagoebizmarts is there a repo for MailChimp For Magento?

**Comment by Santiagoebizmarts** [comment]
https://github.com/mailchimp/mc-magento
