### ISSUE TITLE
String could not be parsed as XML

### ISSUE THREAD

**Issue by richardgrantham26** [ebizmarts/magemonkey#146]
Hey, I have just upgraded to the latest version as recommended, and my new order emails arent being sent out. Error log:

2016-09-07T00:32:12+00:00 ERR (3): 
exception 'Exception' with message 'String could not be parsed as XML' in /chroot/home/concave1/concave.com/html/includes/src/Ebizmarts_MageMonkey_Model_Feed_Updates.php:37
Stack trace:
#0 /html/includes/src/Ebizmarts_MageMonkey_Model_Feed_Updates.php(37): SimpleXMLElement->__construct('<html>\r\n<head><...')
#1 /html/includes/src/Ebizmarts_MageMonkey_Model_Feed_Updates.php(98): Ebizmarts_MageMonkey_Model_Feed_Updates->getFeedData('http://store.eb...')
#2 /html/includes/src/Ebizmarts_MageMonkey_Model_Feed_Updates.php(87): Ebizmarts_MageMonkey_Model_Feed_Updates->_getUpdates('Ebizmarts_Globa...')
#3 /html/includes/src/__default.php(22123): Ebizmarts_MageMonkey_Model_Feed_Updates->check(Object(Varien_Event_Observer))
#4 /html/includes/src/__default.php(22096): Mage_Core_Model_App->_callObserverMethod(Object(Ebizmarts_MageMonkey_Model_Feed_Updates), 'check', Object(Varien_Event_Observer))
#5 /html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#6 /html/includes/src/__default.php(14385): Mage::dispatchEvent('controller_acti...', Array)
#7 /html/includes/src/Mage_Adminhtml_Controller_Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#8 /html/includes/src/__default.php(14261): Mage_Adminhtml_Controller_Action->preDispatch()
#9 /html/includes/src/__default.php(18750): Mage_Core_Controller_Varien_Action->dispatch('index')
#10 /html/includes/src/__default.php(18280): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /html/includes/src/__default.php(21131): Mage_Core_Controller_Varien_Front->dispatch()
#12 /html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /html/index.php(86): Mage::run('', 'store')
#14 {main}

Is this something you could help with? Thanks

**Comment by gonzaloebiz** [comment]
Please follow this [guidelines](https://github.com/ebizmarts/magemonkey/wiki/Issue-reporting-guidelines) and re open the ticket

Thanks
