### ISSUE TITLE
Mandrill transactional emails sending to multiple recipient(s) v1.2.6

### ISSUE THREAD

**Issue by apsx** [ebizmarts/magemonkey#147]
We have an issue on a live site where transactional emails are being sent to multiple (wrong recipients).

My developer has found the code he thinks to be at fault and has left his comments:

Ebizmarts_Mandrill_Model_Email_Queue::getMail()

**********************************
        if ($this->_mail) {
            return $this->_mail;
        } else {
            Mage::helper('ebizmarts_mandrill')->log("store: $storeId API: " . Mage::getStoreConfig(Ebizmarts_Mandrill_Model_System_Config::APIKEY, $storeId));
            $this->_mail = new Mandrill_Message(Mage::getStoreConfig(Ebizmarts_Mandrill_Model_System_Config::APIKEY, $storeId));
            return $this->_mail;
        }

*********************************

$this->_mail is the same Mandrill_Message object for all messages in email queue that are processed... 
that means any call of $mailer->addTo() will add a new email address to the mailing list.

**Comment by Santiagoebizmarts** [comment]
Hello @apsx ,

Thanks for this feedback. It has been solved and we are releasing a new version now.

Regards.
