### ISSUE TITLE
Order e-mail get wrong Sender address

### ISSUE THREAD

**Issue by JoostWan** [ebizmarts/magemonkey#148]
I use the latest version (1.2.6.1) and have some problems with the Sender e-mail (From address). It's get the wrong address. We have a multistore shop and the base (default) store get's the address from a other store. 

Base store: storename@storename.nl
Second store: storename@storename.de 

The base store get's the e-mail sender from the second store. 

It looks like http://ebizmarts.com/forums/topics/view/22855

**Comment by Santiagoebizmarts** [comment]
Hello @JoostWan ,

Indeed it looks like that issue. Did you add the fix explained in that thread at [this post](http://ebizmarts.com/forums/topics/view/22855#22955)?

Regards

**Comment by JoostWan** [comment]
Line 103 is, i don't think that's the right line? 

`            $email ['tags'] = $variables['tags'];`

Thank you

**Comment by Santiagoebizmarts** [comment]
You are right, the correct line on the current version is https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/Mandrill/Model/Email/Template.php#L93

**Comment by JoostWan** [comment]
Strange, still not working. It get only the wrong sender address for the invoice e-mail (Order conformation are disabled). Other mails getting the right sender address.

**Comment by Santiagoebizmarts** [comment]
Hello @JoostWan ,

Do you have that sender domain address for invoices verified on Mandrill?
Can you show explain more in detail where and how did you configured this sender? With screenshots if possible.

Regards

**Comment by Santiagoebizmarts** [comment]
Hi @JoostWan 
If this remains please create a thread on our [forums](http://ebizmarts.com/forums/view/1) or read our [guidelines](https://github.com/ebizmarts/magemonkey/wiki/Issue-reporting-guidelines) to create a fully described issue.
