### ISSUE TITLE
Issue sending non order emails from queue

### ISSUE THREAD

**Issue by TimVroom** [ebizmarts/magemonkey#149]
We are using magento 1.9.2.3 and are having issues with sending emails for everything that is not an order type.
If we look at: https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/Mandrill/Model/Email/Queue.php#L30
thats the only if and if the message is not an order; it wont send.

And only allowing orders to be send through the email queue is not what should happen.

**Comment by TimVroom** [comment]
Probably good to check in the eav_entity_type table to get the appropiate model (if its available)
and otherwise asume its the default admin store (or the current store as in `Mage::app()->getStore()->getId()`

**Comment by TimVroom** [comment]
```
public function getStoreIdByEntity($message)
    {
        switch($message->getEntityType()) {
            case 'order':
                $object = Mage::getModel('sales/order')->load($message->getEntityId());
                $storeId = $object->getStoreId();
                break;
            case 'invoice':
                $object = Mage::getModel('sales/order_invoice')->load($message->getEntityId());
                $storeId = $object->getStoreId();
                break;
            case 'shipment':
                $object = Mage::getModel('sales/order_shipment')->load($message->getEntityId());
                $storeId = $object->getStoreId();
                break;
            case 'creditmemo':
                $object = Mage::getModel('sales/order_creditmemo')->load($message->getEntityId());
                $storeId = $object->getStoreId();
                break;
            default:
                $storeId = (int)Mage::app()->getStore()->getId();
        }

        return $storeId;
    }
```

example function to get the appropiate type/store id. Even though the queue shouldn't be aware of any store...

**Comment by Santiagoebizmarts** [comment]
Hello @TimVroom 
Actually the order email is the only one handled via Magento's queue. The other emails are sent in real time in [this file](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/Mandrill/Model/Email/Template.php).

Please check our [guidelines](https://github.com/ebizmarts/magemonkey/wiki/Issue-reporting-guidelines) and tell us more about the use case where it fails.

Regards.
