### ISSUE TITLE
Disabling mandrill wont allow sending of emails from the queue

### ISSUE THREAD

**Issue by TimVroom** [ebizmarts/magemonkey#150]
If mandrill is disabled in at least 1.9.2.3 no emails are beiing send because of the following line:

https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/Mandrill/Model/Email/Queue.php#L138

The email queue doesn't have a function called getMail() it's using a direct `new Zend_Mail('utf-8');` instead of a wrapped function.

**Comment by Santiagoebizmarts** [comment]
Hello @TimVroom 
You are right about that return being wrong. Anyways that function should not be called if Mandrill is disabled so I don't see the use case where that causes the failure you mention.
