### ISSUE TITLE
No way to choose order status for "After new order" autoresponder

### ISSUE THREAD

**Issue by m-overlund** [ebizmarts/magemonkey#152]
There is no way to choose after which order status the "after new order" autoresponder should be sent.
There's a field missing on the website/store scope - it's only available on the base scope.

![mandrill](https://cloud.githubusercontent.com/assets/504236/20390081/60d4e870-accd-11e6-9975-35849999b503.png)

**Comment by gonzaloebiz** [comment]
Hi @m-overlund 

thanks for your feedback.
Magemonkey is freezed to new features, we are developing Mailhimp4Magento (https://github.com/mailchimp/mc-magento) which support Mailchimp API 3.0.

**Comment by m-overlund** [comment]
It's clearly a bug - the field is missing, so you can't complete the email trigger.
Mailchimp4Magento isn't a solution - it doesn't support multistore.

**Comment by m-overlund** [comment]
The field does exist in base view, but is the only field that's not visible in store view.

![magemonkey](https://cloud.githubusercontent.com/assets/504236/20519110/eb180670-b0a1-11e6-9cf1-c679db90fd9e.png)

**Comment by Santiagoebizmarts** [comment]
Hello @m-overlund 

Thanks for your feedback. This has been fixed. You can see the commit to get the change for yourself at [https://github.com/ebizmarts/magemonkey/commit/a25db9ed4540ea6f6541cadb4d9cb10124fa92c6](https://github.com/ebizmarts/magemonkey/commit/a25db9ed4540ea6f6541cadb4d9cb10124fa92c6)

You will need to refresh your cache afterwards.

Regards.
