### ISSUE TITLE
Mandrill - Bcc handling not correct

### ISSUE THREAD

**Issue by ihor-sviziev** [ebizmarts/magemonkey#153]
Hi,

We're using Mandrill module to send emails. In our magento in Admin >> System >> Configuration >> Sales >> Sales Emails >> Orders section we have "Send Order Email Copy Method" set to "Bcc".
But emails sends separately.

I found article in FAQ of Mandrill API: https://mandrill.zendesk.com/hc/en-us/articles/205582557-Can-I-send-to-more-than-one-recipient-at-a-time-

Looks like in this case we should send "preserve_recipients" attribute with "true" value additionally.

I know that this feature may be risky, so maybe it should be configurable.

**Comment by Santiagoebizmarts** [comment]
Hello @ihor-sviziev ,

Bcc's are sent with the Mandrill library functions. I'm not sure what you mean. Can you show an example of this problem?
This doesn't look like a problem to me.

Regards.

**Comment by ihor-sviziev** [comment]
**Actual result:**
If we set New Order Email sending to "Bcc" mode - new order emails are sent as separate email.

**Expected result:**
If we set New Order Email sending to "Bcc" mode - new order emails should be sent to customer and Bcc to other recipients.

I think it could be done there:
https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/Mandrill/Model/Email/Template.php#L76

Possible solution:
```php

if ($mail->getBcc()) {
    $email['preserve_recipients'] = true;
}
```

I'm not sure, maybe it's not the best solution.

**Comment by Santiagoebizmarts** [comment]
@ihor-sviziev 

As far as I can see in Mandrill docs the email sent as bcc is a copy of the original.
[https://mandrill.zendesk.com/hc/en-us/articles/205582117-How-to-Use-SMTP-Headers-to-Customize-Your-Messages](https://mandrill.zendesk.com/hc/en-us/articles/205582117-How-to-Use-SMTP-Headers-to-Customize-Your-Messages)

> Send a Copy of Every Message Sent to a Single Email Address
> 
> This is Mandrill's built-in Bcc recipient option. With this option enabled, we'll send a blind-carbon-copy of the email (including all tracking information) to the address you specify.

Regards.

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts You can't see who is in Bcc, it's default behaviour. From wiki:

> BCC: blind carbon copy to tertiary recipients who receive the message. **The primary and secondary recipients cannot see the tertiary recipients.** Depending on email software, the tertiary recipients may only see their own email address in BCC, or they may see the email addresses of all primary and secondary recipients.

**Comment by immist** [comment]
@ihor-sviziev do you have any news about your suggested fix? Does it work as expected?
Thanks and best regards!

**Comment by ihor-sviziev** [comment]
@immist sorry, I decided to switch out of magemonkey to fix this issue for me.
