### ISSUE TITLE
No suchfile or directory

### ISSUE THREAD

**Issue by michaelzangerle** [ebizmarts/magemonkey#157]
### Situation - How did you get there?

I have a Magento 1.9.2.1 instance and updated Magemonkey to 1.2.8 to fix some problems. It seems to work mostly fine but I get following error when I open the settings page MageMonkey > MailChimp.

### Problem - What went wrong?

ERR (3): Warning: include(Mage/Admin/Model/Resource/Block/Collection.php): failed to open stream: No such file or directory  in [...]/lib/Varien/Autoload.php on line 94
2016-11-28T13:20:10+00:00 ERR (3): Warning: include(): Failed opening 'Mage/Admin/Model/Resource/Block/Collection.php' for inclusion (include_path=[...]/lib/minify:[...]/app/code/local:[...]/app/code/community:[...]/app/code/core:[...]/lib:.:/usr/share/php')  in [...]/lib/Varien/Autoload.php on line 94

### Possible solution - How should it be?

I found out that it's somehow related to line 31 in app/design/adminhtml/default/default/template/magemonkey/system/config/upgradeforpatch.phtml but as I am no magento dev I'm not sure this is the real issue here.

Thanks.

**Comment by Santiagoebizmarts** [comment]
Hello @michaelzangerle 

You can fix this by commenting [these lines](https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/etc/system.xml#L100-L109). I am not sure why you got this error. It has been tested with your Magento version.

Regards.
