### ISSUE TITLE
Failing magemonkey_webhooks_asynch

### ISSUE THREAD

**Issue by etsanov** [ebizmarts/magemonkey#159]
I get the following error when I run the cron manually:

Catchable fatal error: Argument 1 passed to Ebizmarts_MageMonkey_Model_Cron::_subscribe() must be of the type array, null given, called in /home/grabells/public_html/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php on line 549 and defined in /home/grabells/public_html/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php on line 590

The issue is there when run by cron automatically. I am using 1.2.8. Please help.

**Comment by Santiagoebizmarts** [comment]
Hello,

Looks like you have some corrupted data in one of your tables. Please go to our [forum](https://ebizmarts.com/forums/view/1) and we will get back to you as soon as possible.

Regards,
