### ISSUE TITLE
Customer Account: Impossible add to newsletter after removed.

### ISSUE THREAD

**Issue by pliniocardoso** [ebizmarts/magemonkey#160]
I have one problem with your module, If I access the customer account and remove from list 'mytest' for example, I can't subscribe in the same list again.

I've inspected the code and I found the following error message:
"plynyo@gmail.com has been removed, and cannot be resubscribed by you. To prevent false spam complaints, they'll need to resubscribe of their own free will."

Do you have some solution? I'm the a client for example, I cannot register again?

![002](https://cloud.githubusercontent.com/assets/5747238/22002507/71174c4a-dc44-11e6-838b-b77eeb84b54a.png)

**Comment by pliniocardoso** [comment]
Note: After the user has been subscribed it is impossible for him subscribe or unsubscribe any list. I'm using the Magento ver. 1.9.2.3 and your last module version.

**Comment by clivewalkden** [comment]
This has also been noted as a problem with a couple of my sites. Any chance of a fix?

Kind regards

Clive

**Comment by Santiagoebizmarts** [comment]
Hello @pliniocardoso and @clivewalkden,

This is a problem with the API version used in MageMonkey.
The only solution is to migrate to MailChimp For Magento which is the new module using API 3.0.
It is not compatible with multi-store environments yet but will be soon.

Regards.
