### ISSUE TITLE
cron error - store(NULL)

### ISSUE THREAD

**Issue by m-overlund** [ebizmarts/magemonkey#164]
The magemonkey part of this bundled module has an error which throws an exception, like this one below, everytime the cron job runs.

(Whenever i disable Ebizmarts_Magemonkey it doesn't throw this error)

`
a:3:{i:0;s:0:"";i:1;s:1114:"#0 /public_html/app/code/core/Mage/Core/Model/App.php(848): Mage_Core_Model_App->throwStoreException()
#1 /public_html/app/Mage.php(353): Mage_Core_Model_App->getStore(NULL)
#2 /public_html/app/code/core/Mage/Cron/Model/Observer.php(281): Mage::getStoreConfig('system/cron/sch...')
#3 /public_html/app/code/core/Mage/Cron/Model/Observer.php(72): Mage_Cron_Model_Observer->_processJob(Object(Mage_Cron_Model_Schedule), Object(Mage_Core_Model_Config_Element))
#4 /public_html/app/code/core/Mage/Core/Model/App.php(1358): Mage_Cron_Model_Observer->dispatch(Object(Varien_Event_Observer))
#5 /public_html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Cron_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#6 /public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#7 /public_html/cron.php(78): Mage::dispatchEvent('default')
#8 {main}";s:11:"script_name";s:46:"/public_html/index.php";}
`

**Comment by gonzaloebiz** [comment]
Hi @m-overlund 

thanks for your feedback.
Please follow [this guidelies](https://github.com/ebizmarts/magemonkey/wiki/Issue-reporting-guidelinesl) to report an issue.

Thanks
