### ISSUE TITLE
'Exception' with message 'String could not be parsed as XML'

### ISSUE THREAD

**Issue by bjoly82** [ebizmarts/magemonkey#165]
Mage Monkey version: 1.2.1
Magento version: EE1.12

Our logs have been showing the error below since Dec 12 at 3am.  We have not upgrade MageMonkey since Feb 10, 2016.  While we have not had reports of functionality being affected, this error is generating significant noise in our logs and should be suppressed.  

`exception 'Exception' with message 'String could not be parsed as XML' in /data/www/html/mystore.com/app/code/community/Ebizmarts/MageMonkey/Model/Feed/Updates.php:38
Stack trace:
#0 /data/www/html/mystore.com/app/code/community/Ebizmarts/MageMonkey/Model/Feed/Updates.php(38): SimpleXMLElement->__construct('<html>\r\n<head><...')
#1 /data/www/html/mystore.com/app/code/community/Ebizmarts/MageMonkey/Model/Feed/Updates.php(105): Ebizmarts_MageMonkey_Model_Feed_Updates->getFeedData('http://store.eb...')
#2 /data/www/html/mystore.com/app/code/community/Ebizmarts/MageMonkey/Model/Feed/Updates.php(93): Ebizmarts_MageMonkey_Model_Feed_Updates->_getUpdates('Ebizmarts_Globa...')
#3 /data/www/html/mystore.com/app/code/core/Mage/Core/Model/App.php(1352): Ebizmarts_MageMonkey_Model_Feed_Updates->check(Object(Varien_Event_Observer))
#4 /data/www/html/mystore.com/app/code/core/Mage/Core/Model/App.php(1325): Mage_Core_Model_App->_callObserverMethod(Object(Ebizmarts_MageMonkey_Model_Feed_Updates), 'check', Object(Varien_Event_Observer))
#5 /data/www/html/mystore.com/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#6 /data/www/html/mystore.com/app/code/core/Mage/Core/Controller/Varien/Action.php(532): Mage::dispatchEvent('controller_acti...', Array)
#7 /data/www/html/mystore.com/app/code/core/Mage/Adminhtml/Controller/Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#8 /data/www/html/mystore.com/app/code/core/Mage/Core/Controller/Varien/Action.php(408): Mage_Adminhtml_Controller_Action->preDispatch()
#9 /data/www/html/mystore.com/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#10 /data/www/html/mystore.com/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /data/www/html/mystore.com/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /data/www/html/mystore.com/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#13 /data/www/html/mystore.com/index.php(91): Mage::run('mystore', 'store')
#14 {main}`

This error is affecting the admin panel only.  However, we have not had reports of this error appearing on the frontend nor have we reliably reproduced.  The clear reason for this error is that the API is returning HTML, not XML.  

Has this error been addressed in the most recent version of MageMonkey?

**Comment by Santiagoebizmarts** [comment]
Hello,

Please update your version to the latest and that will be fixed.
