### ISSUE TITLE
magemonkey_autoexport_subscribers task runs forever

### ISSUE THREAD

**Issue by delarosajv** [ebizmarts/magemonkey#33]
Hello,

i've been updating the extension time to time now it works but i have this issue. I see in ecommerce360 "magento sent orders" that ordes synchro works ok but the process never stops. I tried to set max orders to export to minimum and also to run the cron every 4 or 12 hours but the same thing.

It looks that the process completes but it do not finish to execute.

Note: We have more than 250k orders on database

Any help?

Here are the cron process running at this moment:
	magemonkey_autoexport_subscribers	13:00:08	13:00:00	13:10:03	 	 	
RUNNING
	magemonkey_autoexport_subscribers	12:00:08	12:00:00	12:10:04	 	 	
RUNNING
	magemonkey_autoexport_subscribers	11:00:07	11:00:00	11:10:03	 	 	
RUNNING
	magemonkey_autoexport_subscribers	10:00:12	10:00:00	10:10:03	 	 	
RUNNING
	magemonkey_autoexport_subscribers	09:00:08	09:00:00	09:10:03	 	 	
RUNNING
	magemonkey_autoexport_subscribers	08:00:03	08:00:00	08:10:03	 	 	
RUNNING
	magemonkey_autoexport_subscribers	07:00:03	07:00:00	07:10:04	 	 	
RUNNING
	magemonkey_autoexport_subscribers	06:00:04	06:00:00	06:10:03	 	 	
RUNNING
	magemonkey_autoexport_subscribers	05:00:08	05:00:00	05:10:03	 	 	
RUNNING
	magemonkey_autoexport_subscribers	04:00:06	04:00:00	04:10:03	 	 	
RUNNING

Thank you

**Comment by Flyingmana** [comment]
try to execute this specific cron job directly from the cli, for example via magerun or aoepeople/Aoe_Scheduler. If during the cron happens an error, for example memory limit exceeded, then depending on the config it is not messaged correctly.
So if you run it directly from CLI, you can see the php error message.

**Comment by centerax** [comment]
Is this now sorted @Flyingmana ?
