### ISSUE TITLE
Release tags missing

### ISSUE THREAD

**Issue by rbrown** [ebizmarts/magemonkey#35]
Hello, it looks like the latest releases listed on connect haven't been tagged in the repo. I think these are the right commits, .22 I'm not sure from the log which commit would have been used for the release. Also, `<version>in Ebizmarts_MageMonkey.xm wasn't updated to 1.1.25, don't know if it matters.

1.1.25 b11ab91a8b3dc66c82303b41b5286f0792a21a8a
1.1.24 791ba201c3da784604bad3d92cab672a760463f6
1.1.23 990d56db9dd37a6b2733e10db4d123554d4da255
1.1.22 It's not clear

**Comment by Flyingmana** [comment]
to be more precise, they are not listed here: https://github.com/ebizmarts/magemonkey/tags

**Comment by Santiagoebizmarts** [comment]
Thanks for making me notice this. Today a new release will be out and it will be correctly tagged.
