### ISSUE TITLE
Notice: Undefined index: email in app/code/community/Ebizmarts/MageMonkey/Model/Cron.php on line 451

### ISSUE THREAD

**Issue by rbrown** [ebizmarts/magemonkey#36]
So, I haven't finished reading all the way through it yet, but in [sendordersAsync()](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L440)  the `info` object has an index `email` being accessed on lines [451](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L451) and [473](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L473). It looks like in  `Model/Ecommerce360.php` function [logSale](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Ecommerce360.php#L110) the if statement on line [142](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Ecommerce360.php#L142) would let the info object be saved without `email` being set?

Also, the call on line [473](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L473) `->setMcEmailId($info['email'])` it looks like it should be using `email_id` ?

**Comment by Santiagoebizmarts** [comment]
Hello,

@rbrown For next release [447 to 453](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L447-L453) will be removed.

Also [469 to 477](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L469-L477) will be changed to:
            $order = Mage::getModel('monkey/ecommerce')
                ->setOrderIncrementId($info['id'])
                ->setOrderId($orderId)
                ->setMcCampaignId($info['campaign_id'])
                ->setCreatedAt( Mage::getModel('core/date')->gmtDate() )
                ->setStoreId($info['store_id']);
            if(isset($info['email_id'])){
                $order->setMcEmailId($info['email_id']);
            }else{
                $order->setMcEmailId($info['email']);
            }
            $order->save();
        }

@delarosajv This will also be fixed by changing [Line 8](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/AbandonedCart/Block/Popup/Emailcatcher.php#L8) to:

class Ebizmarts_AbandonedCart_Block_Popup_Emailcatcher extends Mage_Core_Block_Template {

**Comment by rbrown** [comment]
@Santiagoebizmarts thanks

**Comment by mkaufmann0815** [comment]
Hello,

we have Magento updated to version 1.9.2.4. Under /var/log/system.log we get the error:

ERR (3): Notice: Undefined index: email  in /app/code/community/Ebizmarts/MageMonkey/Model/Cron.php on line 450

We tried to take the example of the February 4, 2015 form Santiagoebizmarts: 
/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php

But this dont works ...

This is currently stored in the cron.php:

  448              $collection2 = Mage::getmodel('monkey/asyncsubscribers')->getCollection()
  449                  ->addFieldToFilter('processed',array('eq'=>1))
  450                  ->addFieldToFilter('email', array('eq'=>$info['email']));
  451              if(count($collection2) == 0){
  452                  continue;
  453              }

and

 469              Mage::getModel('monkey/ecommerce')
 470                  ->setOrderIncrementId($info['id'])
 471                  ->setOrderId($orderId)
 472                  ->setMcCampaignId($info['campaign_id'])
 473                  ->setMcEmailId($info['email'])
 474                  ->setCreatedAt( Mage::getModel('core/date')->gmtDate() )
 475                  ->setStoreId($info['store_id'])
 476                  ->save();
 477          }

Can anyone help me?

Thx

**Comment by rbrown** [comment]
Hi, 
1) You've posted on a two year old closed issue
2) Have you upgraded to the latest version of the extension? v1.2.6.1

**Comment by mkaufmann0815** [comment]
Hi rbrown,

my problem is that does not appear in the Extension [MagentoConnect](https://www.magentocommerce.com/magento-connect/magemonkey.html).

When trying to install them again, there was a message that the files are already present and an installation can not be performed.

The actual installation was not performed by me. We only update the store.

Where can I find the current version?

For a tip I would be grateful!

Thx

**Comment by rbrown** [comment]
tarballs for releases can be directly downloaded from the [releases page](https://github.com/ebizmarts/magemonkey/releases)  but you should really be using [composer](http://alanstorm.com/php_composer_magento_tutorial) to manage your extensions

**Comment by Santiagoebizmarts** [comment]
Hello @mkaufmann0815 ,

Looks like you request should be directed into learning how to update the extension.
Please check our [guidelines](https://github.com/ebizmarts/magemonkey/wiki/Issue-reporting-guidelines) on how to handle issues and questions.
This is more of a forum question than an issue.

Thanks @rbrown for your help. Your responses are right and very helpful.

Regards.

**Comment by mkaufmann0815** [comment]
Hi Santiagoebizmarts,

sorry and thx rbrown!
