### ISSUE TITLE
Helper getMergeVars Results in Very Slow Order Save Transaction With Large Databases

### ISSUE THREAD

**Issue by ltcdnunez** [ebizmarts/magemonkey#39]
I've got this extension installed on a Magento EEv1.12.0.2 store that has a `sales_flat_order` table containing more than 500,000 order records. The `updateCustomer` method from the observer model in this extension hooks into the `_afterSave` event for the `saveOrder` transaction and runs a SQL query against the `sales_flat_order` table that takes upwards of 9 seconds because it is scanning the entire table (or its indexes). The [offending code](/ebizmarts/magemonkey/blob/85ecc0e4db01fb0267e28935f13112b809edbeb7/app/code/community/Ebizmarts/MageMonkey/Helper/Data.php#L471-L476) is using a very inefficient method to get the last order for a particular customer email:

```php
$last_order = Mage::getResourceModel('sales/order_collection')
  ->addFieldToFilter('customer_email', $customer->getEmail())
  ->addFieldToFilter('state', array('in' => Mage::getSingleton('sales/order_config')
  ->getVisibleOnFrontStates()))
  ->setOrder('created_at', 'desc')
  ->setPageSize(1)
  ->getFirstItem();
```

I don't know the inner workings of the extension well enough to know what else would be available in this context, but it seems that if this is being triggered by the order save event, there should already be order data available without having to run a separate query to the database here. The data from the observer object that's being injected into the `updateCustomer` method, for instance, should probably already contain the data from the last created order, so perhaps there's a better way to get this information than running a separate query that scans the entire `sales_flat_order` table.

The sequence of events seems to approximately look like this:

```
save (Mage_Core_Model_Abstract) <- Order
_afterSave (Mage_Core_Model_Abstract)
...
updateCustomer (Ebizmarts_MageMonkey_Model_Observer)
mergeVars (Ebizmarts_MageMonkey_Helper_Data)
getMergeVars (Ebizmarts_MageMonkey_Helper_Data)
```

The slow SQL query is happening in the `getMergeVars` method of the helper, which is ultimately called from the `updateCustomer` method. I would love some feedback from someone who's more familiar with the extension since the update customer observer is likely observing more than just order save events and naturally needs to account for various circumstances.

**Comment by Santiagoebizmarts** [comment]
Hello @ltcdnunez,

This is done and will be available on the next release.
You can see the commit here: https://github.com/ebizmarts/magemonkey/commit/0922e170e502b3d00b71ef033382ce6ac3b2af62

Thanks again for your feedback.
