### ISSUE TITLE
Haven't ability to unsubscribe customers via admin

### ISSUE THREAD

**Issue by ihor-sviziev** [ebizmarts/magemonkey#41]
*Steps to reproduce:*
1. Go to admin --> Newsletter --> Newsletter Subscribers
2. Select one subscriber
3. In "Actions" select "Unsubscribe" and click "Submit" button

*Actual result:*
Subscriber shows as unsubscribed in admin, but it still subscribed on MailChimp.

*Expected result:*
Subscriber shows as unsubscribed in admin and in MailChimp.

Looks like same issue people reported there: http://ebizmarts.com/forums/topics/view/14756/ but this fix isn't working because we didn't have customer model save:
```php
$subscriber = Mage::getModel('newsletter/subscriber')->load($subscriberId);
$subscriber->unsubscribe();
```

**Comment by centerax** [comment]
@ihor-sviziev Can you confirm the fix provided fixex the problem?

**Comment by Santiagoebizmarts** [comment]
@ihor-sviziev You can unsubscribe from the General list from Newsletter -> Newsletter Subscriber. This solves your problem right?
A new release will be out before the weekend. You can download MageMonkey from this repo and install it manually.
