### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by ihor-sviziev** [ebizmarts/magemonkey#43]
In your contributing.md  you say that code style should be according to PSR. In [PSR-2](https://github.com/ebizmarts/magemonkey/blob/master/CONTRIBUTING.md#code-style--git--versions) we have next text:
```
Code MUST use 4 spaces for indenting, not tabs.
```

Using in some places tabs, in other - spaces brakes code formatting on github, example: https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L22

I think there should be used only spaces. Most IDE's support automatic replace.

**Comment by centerax** [comment]
Whats the status of this @Santiagoebizmarts ?

**Comment by Santiagoebizmarts** [comment]
@ihor-sviziev I just downloaded the code and it has the right spacing. I am not sure why it is being shown like this on github. I'll check it out.
Sorry about the delay.

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts that file that I provided contains tabs and spaces, Please look at my link

**Comment by centerax** [comment]
Thanks for pointing this out @ihor-sviziev We will solve this shortly.

**Comment by Santiagoebizmarts** [comment]
The code is now properly spaced. Thanks for helping us improving @ihor-sviziev.
You can see the commit https://github.com/ebizmarts/magemonkey/commit/883778c1b39e3dbd75e53b400b41bfaf3625892c

**Comment by ihor-sviziev** [comment]
:+1:
