### ISSUE TITLE
Send subscribe/unsubscribe mails is broken

### ISSUE THREAD

**Issue by ihor-sviziev** [ebizmarts/magemonkey#44]
In original implementation of magento we have enabled ability to send subscribe/unsubscribe mails. After install MageMonkey module this functionality stops works. I think it's may be because in some places we use 
```php
$subscriber->setImportMode(TRUE);
```

Example: https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L77

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts I think it should be configurable, because for now it's regression of Magento functionality.

**Comment by Santiagoebizmarts** [comment]
@ihor-sviziev I'll see if this can be done for next release or maybe the next one.

Regards,
Santiago.

**Comment by Santiagoebizmarts** [comment]
This is done for next release. You can see a fix for right now at http://ebizmarts.com/forums/topics/view/15823#15953

Regards.

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts is it available on GitHub?

**Comment by Santiagoebizmarts** [comment]
@ihor-sviziev 
Sorry for the delay on this.
The changes you are looking for are at https://github.com/ebizmarts/magemonkey/commit/5363e76205ec98b0b5614b9bfca4dc0073c5c13f
