### ISSUE TITLE
allow to ignore old orders for magemonkey ecommerce360 export

### ISSUE THREAD

**Issue by Flyingmana** [ebizmarts/magemonkey#45]
We have a lot of old orders, and its probably the same for others.
This Orders are not needed for ecommerce360, as there is no related tracking at magemonkey.

It would be nice, if you allow to configure a date or order ID and older entries are ignored for syncing

**Comment by Santiagoebizmarts** [comment]
Hello,

The orders will be exported just once so it shouldn't generate problems.
If you choose to send all orders it will send future orders only.

Best regards,
Santiago.

**Comment by Flyingmana** [comment]
Hi,

the problem is, that I dont feel well to share all financial data of the past years when I only intend to try/use the campaign tracking.

The correct answer would have been, that in the newest version you can also chose "Referred Orders" for "Enable Ecommerce360" and thx to the "checkout_async" which is 1 by default, it is also not blocking the checkout process.

sorry for the noise, and great work you have done

**Comment by Santiagoebizmarts** [comment]
@Flyingmana I'll see what can be done about this for future releases.

Thanks for helping us to improve MageMonkey.

**Comment by centerax** [comment]
is this working as you expect @Flyingmana ?
