### ISSUE TITLE
cron magemonkey_sendorders_asynch does not process orders

### ISSUE THREAD

**Issue by Flyingmana** [ebizmarts/magemonkey#46]
The reason seems to be that our magemonkey_async_subscribers table is empty, because this code skips an order without an related subscriber which already got processed.
https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L451

Is this a bug, oder is there some action needed if I updated from an older version?

**Comment by Flyingmana** [comment]
possible related posts:
http://ebizmarts.com/forums/topics/view/15751

**Comment by Santiagoebizmarts** [comment]
Hello, that filter will be out on today's release so it shouldn't be a problem anymore.
