### ISSUE TITLE
add option to prefill newsletter checkbox in checkout depending on customer newsletter state

### ISSUE THREAD

**Issue by Flyingmana** [ebizmarts/magemonkey#49]
In the case a Customer is already registered for Newsletter.

Currently the checkbox only has the predefined state from the config, even if the customer is already registered for the Newsletter.

I want the additional option:
* hide checkbox when customer is already registered for newsletter

**Comment by augsteyer** [comment]
I am assuming you are talking about the checkbox on the checkout page? That should be handled by magento automatically if the customer is already subscribed to the newsletter. Do you have a custom checkout page?
