### ISSUE TITLE
Logo for configuration tab served over http (not https)

### ISSUE THREAD

**Issue by ckressibucher** [ebizmarts/magemonkey#50]
Please use https to fetch the logo for the system configuration tab, if the site uses https. Otherwise we get a warning because of unsecure content from the browser.

(e.g. in app/design/adminhtml/default/default/template/magemonkey/system/config/fieldset/hint.phtml)

thanks

**Comment by Santiagoebizmarts** [comment]
This is done and will be ready for next release.
Thank you very much.
