### ISSUE TITLE
Undefined index: email_address

### ISSUE THREAD

**Issue by SchumacherFM** [ebizmarts/magemonkey#54]
Just saw in my log file this:

```
2015-02-22T09:35:14+00:00 ERR (admin): /monkey/webhook/index/wkey/87263482634623default/
REQUEST: redacted
TIME: 0.083178s
ADDRESS: xxx.201.132.xxx
USER AGENT: MailChimp.com
FILE: htdocs/app/code/core/Mage/Core/functions.php:247
Notice: Undefined index: email_address  in app/code/community/Ebizmarts/MageMonkey/Helper/Cache.php on line 107
```

I could change the method `cacheTagForCommand ()` to add an isset check but I don't know of the side effects. Please check for a fix.

Thanks!

**Comment by Santiagoebizmarts** [comment]
Do you happen to know what caused this?

**Comment by SchumacherFM** [comment]
No :-(

**Comment by centerax** [comment]
Okay, @gonzaloebiz Will try to replicate.

**Comment by Santiagoebizmarts** [comment]
@SchumacherFM After some research it doesn't seem like this error could show up unless you did a customization to the module. Redacted won't be processed by MageMonkey.
