### ISSUE TITLE
Bug in SQL query Ebizmarts_AbandonedCart_Model_Cron::_process

### ISSUE THREAD

**Issue by SchumacherFM** [ebizmarts/magemonkey#55]
At this [line 110](https://github.com/ebizmarts/magemonkey/blob/master/app%2Fcode%2Fcommunity%2FEbizmarts%2FAbandonedCart%2FModel%2FCron.php#L110):

```
if (count($customergroups)) {
    $collection->addFieldToFilter('main_table.customer_group_id', ['in', $customergroups]);
}
```

it must be:

```
if (count($customergroups)) {
    $collection->addFieldToFilter('main_table.customer_group_id', ['in' => $customergroups]);
}
```

**Comment by centerax** [comment]
Thanks Cyrill, we will review this and apply the fix for next release.

**Comment by centerax** [comment]
we are still going to do this on our official repo.

**Comment by Santiagoebizmarts** [comment]
@SchumacherFM This is done. Commit https://github.com/ebizmarts/magemonkey/commit/c3c25a3ea8cbba67b2bd535086125717d84addb2#diff-0721a46ebdcf953242d2d2e60d73d395R128

Thanks for your continued feedback.
