### ISSUE TITLE
Please use Mage::getModel

### ISSUE THREAD

**Issue by SchumacherFM** [ebizmarts/magemonkey#56]
instead of hardcoded class name: https://github.com/ebizmarts/magemonkey/blob/master/app%2Fdesign%2Ffrontend%2Fbase%2Fdefault%2Ftemplate%2Febizmarts_abandonedcart%2Femail%2Forder%2Fitems.phtml#L35

please use `Mage::getModel()`

Thank you :-)

**Comment by centerax** [comment]
Thanks for your feedback Cyrill, we will sort this out shortly.

**Comment by Santiagoebizmarts** [comment]
@SchumacherFM This is done. Commit https://github.com/ebizmarts/magemonkey/commit/b68efca7b5b2957617c424553f7d3dc1b77701da

**Comment by SchumacherFM** [comment]
:+1:
