### ISSUE TITLE
Polluting log file

### ISSUE THREAD

**Issue by SchumacherFM** [ebizmarts/magemonkey#59]
In class `Ebizmarts_Mandrill_Model_Email_Template ` on line [132](https://github.com/ebizmarts/magemonkey/blob/master/app%2Fcode%2Fcommunity%2FEbizmarts%2FMandrill%2FModel%2FEmail%2FTemplate.php#L132) is a `Mage::log` call which pollutes the log file.

Can this please be removed or make it at least configurable to disable the output?

Thanks!

**Comment by centerax** [comment]
@SchumacherFM You can control this by disabling the magento general developer logs.

**Comment by Santiagoebizmarts** [comment]
@SchumacherFM This will be sent on Mandrill log file from now on. Commit https://github.com/ebizmarts/magemonkey/commit/fd6733efefc971b4f6404f3c7e4708b28d3a96a8

**Comment by SchumacherFM** [comment]
Cool thanks!

Disabling the general developer logs is a suboptimal idea ...
