### ISSUE TITLE
Tags have fallen behind version

### ISSUE THREAD

**Issue by clockworkgeek** [ebizmarts/magemonkey#60]
Hi and thanks for the extension.  I currently have 3 projects which use it.  I appreciate the summary written in each release/tag which makes my job easier.

I notice there have been 4 versions since the last tag so [Composer is out of date](http://packages.firegento.com/#!/ebizmarts/magemonkey).  Please write some more of those useful tags.

**Comment by Santiagoebizmarts** [comment]
@clockworkgeek The latest tag was just released and will be set on each release again from now on.
Sorry for the troubles.

**Comment by clockworkgeek** [comment]
I am very grateful.
