### ISSUE TITLE
Ecommerce360 catalog data

### ISSUE THREAD

**Issue by alihalabyah** [ebizmarts/magemonkey#62]
Hello,

We're trying to enable the `Ecommerce360` in order to push the catalog data to Mailchimp by switching `Enable Ecommerce360` for `All Orders` but the issue here is that when checking the `MageMonkey_ApiCall.log` the orders being sent once a new order is placed are all old ones or not exist,  Is there a way to flush the order data saved in the custom tables of the extension `magemonkey_ecommerce360` and `magemonkey_async_orders` however I'm not sure which one of these are responsible about sending the data to Mailchimp!

**Comment by centerax** [comment]
Thanks for your feedback @alihalabyah.
@Santiagoebizmarts will check if this is an actual issue and we will provide a solution as soon as we can.

Thanks again,
Pablo // CTO

**Comment by Santiagoebizmarts** [comment]
@alihalabyah There is a button on MailChimp configuration to remove all local orders to start sending after that moment. You can see this at https://sites.google.com/a/ebizmarts.com/wiki-en/magemonkey/configuration?pli=1#TOC-Reset-Orders-Ecommerce360.

Let me know if this is what you meant please.

Regards,
Santiago.

**Comment by alihalabyah** [comment]
Hello @Santiagoebizmarts,

First of all thank you for mentioning the buttons that can remove the local and the remote orders.

I've noticed that the default value for `checkout_async` is `1` by default and the `logSale` method in `Ecommerce360.php` uses the `checkout_async` value to decide whether to send the order data directly or to add it so that it can be sent in the next cron cycle.

After disabling the checkout async option, the orders started to appear in mailchimp

**Comment by centerax** [comment]
Thanks for the information @alihalabyah, I'm closing this issue considering it resolved, feel free to reopen  if you need to.
