### ISSUE TITLE
Adding 25k subscribers via MageMonkey

### ISSUE THREAD

**Issue by mobweb** [ebizmarts/magemonkey#63]
We need to add about 25k existing customer accounts from Magento to our MailChimp account.

Do you think this should be possible using MageMonkey/Magento to add the subscribers via the API, or should we look into manually uploading the subscribers to Mailchimp?

If we have to manually upload the subscribers, can you tell us if their customer accounts will be linked to their Mailchimp subscription? So if we unsubscribe them via Magento/MageMonkey, will they get unsubscribed from Mailchimp correctly?

Thank you!

**Comment by centerax** [comment]
Thanks for your fredback mobweb but I would like to ask you to create a topic on http://ebizmarts.com/forums/view/2 that's our support channel, this issues on github are code related issues

Thanks.
