### ISSUE TITLE
Spurious request to API creating entries in the API log. 

### ISSUE THREAD

**Issue by andrewhowdencom** [ebizmarts/magemonkey#64]
### Situation - How did you get there?
Running the asyncSubscribe method through a controller as part of the debugging process. 

### Problem - What went wrong?
If there is only a single record the $batch[] variable will not have any data. The extension posts to Mailchimp API anyway, creating a spurious "There's no batch" log entry: 

    [2015-04-09 00:21:28] MageMonkey_ApiCall.DEBUG: Array (     [0] => Error: You must specify a batch value for the listBatchSubscribe method, code -90     [__pid] => 2673 )  [] []

https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L521
    
(Caveat: I've messed with the logging, thus the formatting has changed)

### Possible solution - How should it be?
Check to see if $batch is set before making the request to the API.

**Comment by centerax** [comment]
Thanks @andrewhowdencom 

We will check this and share our thoughts as soon as we can.

**Comment by Santiagoebizmarts** [comment]
@andrewhowdencom Thanks for noticing this.
You can see the commit https://github.com/ebizmarts/magemonkey/commit/fab65e4e1e81a443e97bb130a92f47e34939fa7c
