### ISSUE TITLE
No error logging for API errors.

### ISSUE THREAD

**Issue by andrewhowdencom** [ebizmarts/magemonkey#65]
### Situation - How did you get there?
Trying to work out why a user subscription was unsuccessful. 

### Problem - What went wrong?
- User had unsubscribed (me, earlier). 
- User had subscribed but not confirmed, thus not showing up in Mailchimp but not being added successfully by Mage Monkey. 

There's no logging of this, though. The errors are silently discarded.

### Possible solution - How should it be?
It would be good if they were logged, and (bonus points) available for the admin to review at some stage. I only found out debugging through the magic __call method.

Put the logging of errors in the magic __call method? I don't think anything else logs, and it's known there that there's an error. 

Ref: https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L534

**Comment by Santiagoebizmarts** [comment]
Hello @andrewhowdencom,

Sorry about the delay.
Let me walk through each step to see if this is what you mean.

1) A User subscribes to the list correctly.
2) He/she unsubscribes correctly.
3) He/she subscribes again without confirming the email.

I don't understand what is not working there. The subscriber shouldn't be on MailChimp list because the email was not confirmed.

**Comment by andrewhowdencom** [comment]
Hey @Santiagoebizmarts -- Sorry about the delay getting back to you. 

I haven't got the code in front of me anymore, however, it went as you say: 
   1) Subscribe through MageMonkey
   2) Unsubscribe through MailChimp (not delete)
   3) Subscribe through MageMonkey again 

However, MailChimp does not allow complete (non two-step) re-subscription for users who have un-subscribed (see  [discussion](https://groups.google.com/forum/#!msg/mailchimp-api-discuss/SKKUWOnzNdw/_kCam_nAO1kJ) for another example)

Ideally, I think it'd be good to have some error handling around [this method call](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Cron.php#L537) checking to see if the result was successful, however, in retrospect it's [likely it was in the api logs](https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Api.php#L143). I remember looking at it at the time and thinking something like 
``` 
    $result = Mage::getSingleton('monkey/api')->superApiMethod($var);
    if ($result !== null && $result->getError() !== null) {
        Mage::helper('monkey')->log(sprintf(self::ERR_API_CALL_FAILED, $result->getError(), Zend_Log::WARN); 
    }
```
would have made life a bit easier, though if it was in the api log it might not be worth it. I will not be revisiting this code in the immediate future, you're welcome to close this issue!
