### ISSUE TITLE
Split the Extensions

### ISSUE THREAD

**Issue by andreasemer** [ebizmarts/magemonkey#66]
Currently there are five extensions in the extension for Mailchimp which is very annoying, because most of the merchants will definitely not use all of the products of Mailchimp or Sweetooth. I would recommend to split these extensions in different code pools.

**Comment by Santiagoebizmarts** [comment]
Hello @andreasemer,

Thanks for your feedback.
Are you having troubles with any particular module?
You don't need to enable all the modules. You can only enable the ones you want to use.
MageMonkey is a complete mailing solution to every store and that is why all the modules are in one extension.

**Comment by andreasemer** [comment]
I know that i can enable just particular modules. But in any ways this would mess up the current code pool with unnecessary code. In my case i have changed the Modman file to just deploy one needed part (MageMonkey), but in general this is not a good practice practice. I think the most developers would recommend to have a lean and clean code structure.

**Comment by Santiagoebizmarts** [comment]
Sorry to hear about your issues but actually it's a common practice, many developers bundle extensions the way we do and to be honest this is the first time we get a complain of this nature even though there are over 20K Magento stores using it. We won't change the way we distribute MageMonkey I'm afraid.
