### ISSUE TITLE
When adding NL subscribers in the backend, the Store View specific list settings are ignored

### ISSUE THREAD

**Issue by mobweb** [ebizmarts/magemonkey#70]
I have one Website with three Store Views:

- Store View A
- Store View B
- Store View C

In Mailchimp, I have three subscriber lists, one for each Store View:

- List A
- List B
- List C

In the configuration, I have added my Mailchimp account in the default configuration. I have selected List A as the default list. In the settings for Store Views B and C I have selected the respective lists.

In the frontend, when I am in Store View A and subscribe to the NL, the email is correctly added to the List A. The same for Store View B (List B) and Store View C (List C).

In the backend, when I select a customer that is assigned to Store View B and click "Subscribe to Newsletter", the email is added to Mailchimp's "List A", which is the one that is defined in the default settings.

So it seems like when working in the backend, the Store View specific settings are ignored, and the default settings are used instead.

Any chance of a fix? Multi-website or multi-language shops will always require different lists per Store View or Website...

**Comment by Santiagoebizmarts** [comment]
I am closing this issue because is a copy of https://github.com/ebizmarts/magemonkey/issues/61.

Thanks for the feedback @mobweb
