### ISSUE TITLE
Warning: include(Mage/Rewards/Model/Customer.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by leek** [ebizmarts/magemonkey#74]
`grep`ing the codebase shows only **Ebizmarts** extensions referencing `rewards/customer`. Can you add a proper check for if that extension is enabled before loading its models?

**Comment by Santiagoebizmarts** [comment]
@leek Thanks for your feedback. You can see this committed in our develop branch https://github.com/ebizmarts/magemonkey/commit/5c713289e9114f480471209b911f4c9db8a9b5d0
