### ISSUE TITLE
Wrong directory name in modman file

### ISSUE THREAD

**Issue by vmasciotta** [ebizmarts/magemonkey#77]
Hi all,
there is a typo error in the modman file https://github.com/ebizmarts/magemonkey/blob/master/modman#L34 in commit f10dd76fd932c540dee780ff8fe7cd615260e4bd.
Once update through composer You get error *directory does not exist*, in modman the directory name should be *autoresponders*.

Bye.

**Comment by Santiagoebizmarts** [comment]
@vmasciotta Thank you very much!
This was updated into our develop branch, commit https://github.com/ebizmarts/magemonkey/commit/babb15ea7c69b3b9693ef9b07dd01a89f6b8ba80
