### ISSUE TITLE
Typo in modman (line 34, js/ebizmarts/autoresponder)

### ISSUE THREAD

**Issue by pnlimesoda** [ebizmarts/magemonkey#80]
Hi, getting this error when installing with composer:

[ErrorException]
Source ebizmarts/magemonkey/js/ebizmarts/autoresponder does not exist

Seems that in modman file on line 34 there's a typo: js/ebizmarts/autoresponder should be js/ebizmarts/autoresponders (s missing)

**Comment by Santiagoebizmarts** [comment]
@pnlimesoda Thanks for your feedback. This has been already commited into our develop branch and will be merged soon.
Your help is really appreciated, you can see the commit at https://github.com/ebizmarts/magemonkey/commit/babb15ea7c69b3b9693ef9b07dd01a89f6b8ba80
