### ISSUE TITLE
Spelling in modman file - js/ebizmarts/autoresponder(s)

### ISSUE THREAD

**Issue by josh-carter** [ebizmarts/magemonkey#81]
`js/ebizmarts/autoresponder`                                             `js/ebizmarts/autoresponder`

Should be :

`js/ebizmarts/autoresponders`                                             `js/ebizmarts/autoresponders`

(Notice the 's' on the end)

**Comment by Santiagoebizmarts** [comment]
@josh-carter Thanks for this. We already commited this into our develop branch. It will be ready in our next release.

Kind Regards,
Santiago.

**Comment by razbakov** [comment]
I opened #86 because it is still broken on master and last stable release.
Please remove mark "stable release" from v1.1.34
