### ISSUE TITLE
Notice: Undefined variable: guestFirstName in app/code/community/Ebizmarts/MageMonkey/Helper/Data.php on line 425

### ISSUE THREAD

**Issue by razbakov** [ebizmarts/magemonkey#85]
because of this:
https://github.com/ebizmarts/magemonkey/commit/31ac256d708ead9c70e2eba3a79774f88388ba9d#diff-e2f953188b065b130e376b338259ac52R421

**Comment by Santiagoebizmarts** [comment]
@razbakov To fix this issue check this new commit in our develop branch. It will be merged when the next release is done.
Commit: https://github.com/ebizmarts/magemonkey/commit/f6ed26205e26327d24be6881e049284708180a35
