### ISSUE TITLE
Composer: [ErrorException] Source vendor/ebizmarts/magemonkey/js/ebizmarts/autoresponder does not exist

### ISSUE THREAD

**Issue by razbakov** [ebizmarts/magemonkey#86]
tag: 1.1.34
error in modman:
`js/ebizmarts/autoresponder`
should be 
`js/ebizmarts/autoresponders`

**Comment by razbakov** [comment]
Please remove mark "stable release" from v1.1.34

**Comment by razbakov** [comment]
or add a hotfix please

**Comment by Santiagoebizmarts** [comment]
@razbakov 

Thanks for your feedback.
That is added in our master branch. You can see it at https://github.com/ebizmarts/magemonkey/blob/master/modman#L34

It will also be on the next tag release.
