### ISSUE TITLE
Support for mandrill scheduling

### ISSUE THREAD

**Issue by simonr44** [ebizmarts/magemonkey#88]
Do you have any plans to implement support for Mandrill Scheduling based on message tags?
This feature may be very useful for many merchants.
https://mandrill.zendesk.com/hc/en-us/articles/205582667-Can-I-schedule-a-message-to-send-at-a-specific-time-

It would be possible using the send_at parameter which could be configured on a per tag basis?

**Comment by Santiagoebizmarts** [comment]
@simonr44 Thanks for contacting us. How do you plan on using this? I don't see what value this will add to the service. Autoresponder emails already have a configuration to send emails at a certain time.
Abandoned Cart has an amount of hours to send an email after a customer abandons a cart.
Which emails should have this option in your opinion?

**Comment by simonr44** [comment]
Thanks for considering this option,

We have found that our open rates and click rates improve at certain times of the day, as well as on certain days of the week. We would like to schedule certain emails to be sent at the same time each evening. The ability to alter this time would allow us to fine tune the engagement.

As an example we would like to schedule our Autoresponder review and email stock alerts to send at a certain time each evening that would best suit our customers. 

Another tag that would be of interest to us would be the magento shipping email, default_sales_email_shipment_template. If these were scheduled to go at a set time each day e.g. (6:30pm monday to friday only) we could improve the open rate and ensure our customers absorb the information contained.

The ability to set this on a per tag basis would make the mandrill extension even more powerful from a marketing point of view.

**Comment by Santiagoebizmarts** [comment]
This feature will be considered for Magento 2. We are not adding new features to Magento 1 for now.
