### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by AydinHassan** [ebizmarts/magemonkey#90]
Hi, can you tag a new release with the modman mapping fix in please? We don't want to rely on `dev-master`

Thanks!

**Comment by Santiagoebizmarts** [comment]
@AydinHassan This will be done tomorrow to solve some minor issues first.

**Comment by AydinHassan** [comment]
@Santiagoebizmarts Sounds good, thanks!

**Comment by Santiagoebizmarts** [comment]
@AydinHassan Sorry for the delay on this. Here is the new release for this version https://github.com/ebizmarts/magemonkey/releases/tag/1.1.34

**Comment by AydinHassan** [comment]
No problem, thanks for ping :)
