### ISSUE TITLE
Mailchimp extension isnt pulling the old subscribers from the magento newsletter subscribers

### ISSUE THREAD

**Issue by mkumar11** [ebizmarts/magemonkey#91]
Mailchimp extension isnt pulling the old subscribers from the magento newsletter subscribers.
please suggest me.

Thanks

**Comment by Santiagoebizmarts** [comment]
Hello @mkumar11,
To do this you just need to follow the steps explained in our wiki: http://wiki.ebizmarts.com/magemonkey/faq#TOC-How-Can-I-sync-subscribers-in-Magento-with-MailChimp-

**Comment by mkumar11** [comment]
Hello @Santiagoebizmarts 
 
ran the MC export, it says for status IDLE

followed the instructions in the link given but didn't work.

**Comment by Santiagoebizmarts** [comment]
If after 15 minutes that status didn't change then you need to configure your Magento cron jobs as explained at http://support.xtento.com/wiki/Setting_up_the_Magento_cronjob
