### ISSUE TITLE
Subscribe with other Checkout

### ISSUE THREAD

**Issue by ahmadalkaid** [ebizmarts/magemonkey#92]
Hi Guys,

We have custom checkout, but we couldn't find a way to subscribe with mail chimp extension through our checkout. Is that couldn't happened because I found a condition in the Helper/Data.php 
elseif (Mage::getSingleton('core/session')->getIsOneStepCheckout() && Mage::helper('monkey')->config('checkout_subscribe') > 2 && !Mage::getSingleton('core/session')->getIsUpdateCustomer())
So could you please explain to me how we will connect our checkout with your extension?? or is that should be from our side??

Best,
-Ahmad al-kaid

**Comment by Santiagoebizmarts** [comment]
@ahmadalkaid 
You can add a flag at https://github.com/ebizmarts/magemonkey/blob/1.1.34/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L422-L443
Then check your flag in the mentioned elseif at Data.php and you should get it working.

Regards.

**Comment by ahmadalkaid** [comment]
Hi @Santiagoebizmarts,

The Issue we are facing now, that we override one step checkout . so the part you are calling from the observer is not there now. so what do you think is the best solution for this?? is there a way to call this function in our checkout?? But that may cause some issues if your extension is not used by one of our merchants, so what do you think??

**Comment by Santiagoebizmarts** [comment]
Hello,

That variable session is from MageMonkey not from OSC.
I can't help you with custom modules I don't know how it works.
Sorry.

**Comment by ahmadalkaid** [comment]
Hi @Santiagoebizmarts ,

If it could help, I could give you testing site just to look how we build it. And provide us with some notice on how we could fix this enhancement, cause many of our merchants asked for this one .

URL :   http://demo.staging.shopgo.io/
please try just to check or checkout from the front end and see the section we over ride it .

Thanks :)

**Comment by Santiagoebizmarts** [comment]
The problem here is that you customized a custom module. I can't be sure on how everything is done. I can help you with the specific questions only. For example I can tell you that whenever you set the subscribe($email); function from a subscriber that triggers our module at https://github.com/ebizmarts/magemonkey/blob/1.1.34/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L19
