### ISSUE TITLE
Subscribe On Checkout doesn't work correctly

### ISSUE THREAD

**Issue by vmasciotta** [ebizmarts/magemonkey#93]
If Subscribe On Checkout is disabled and a customer complete an order (paying with PayPal), he will subscribe automatically the newsletter. Is this the correct behavior?

**Comment by Santiagoebizmarts** [comment]
No it's not. Maybe you selected the force subscribe before and after changing it back you didn't flush your Magento cache. If this is the case try flushing it and then test again please.

**Comment by vmasciotta** [comment]
Thank You for your quick answer! 
I've tried what You suggested me, but it's not working. And, my mistake, it doesn't work not only with PayPal but with the other payment methods too. 
I'm on magento 1.9.2.1
Thanks

**Comment by Santiagoebizmarts** [comment]
Do you have any other extension affecting the checkout?
Can you tell me the url of the store?

**Comment by donalt** [comment]
We are also experiencing this and can't seem to work out the cause.

@vmasciotta Is it worth comparing installed extensions and configuration to see whether there's a commonality between our sites?

@Santiagoebizmarts Is there a way to enable very verbose logging or something else to help us debug?

Thanks,
Dónal

**Comment by Santiagoebizmarts** [comment]
@donalt Unfortunately there is no other log than MageMonkey_ApiCall.log. Since it's happening in the checkout I'm pretty sure that the problem starts at https://github.com/ebizmarts/magemonkey/blob/1.1.34/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L422
Then it goes to https://github.com/ebizmarts/magemonkey/blob/1.1.34/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L451
to finally goes to the subscription observer at https://github.com/ebizmarts/magemonkey/blob/1.1.34/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L19

Maybe that can help you guys find out the issue.
If that doesn't help I can give you more personalized support sending an email explaining that I asked you to send it from this github issue.

Since this is happening for more that one person it's best to solve it to avoid future cases.

Regards,
Santiago.

**Comment by vmasciotta** [comment]
Hi all,
I can't investigate more right now, I should be able to do it during the next week.
@donalt @Santiagoebizmarts this is a list of all the extensions I loaded into that project (extracted from project composer).
```javascript
{
...
  "require": {
    "php": ">=5.5",
    "magento/core": "~1.9.2",
    "aydin-hassan/magento-core-composer-installer" : "~1",
    "magento-hackathon/magento-composer-installer": "~3",
    "vmasciotta/magento-italianlocale" : "dev-master",
    "phoenix-media/magento-bankpayment": "dev-master",
    "phoenix-media/magento-cashondelivery":"dev-master",
    "netzarbeiter/nicer-image-names": "dev-master",
    "firegento/dynamiccategory": "dev-master",
    "firegento/magesetup":"~2",
    "n98/magerun": "~1",

    "vmasciotta/magento-provinceitaliane": "dev-master",
    "vmasciotta/magento-pdfinvoicedate": "dev-master",
    "vmasciotta/fiscale-italia":"dev-develop",
    "amasty/product-parts-finder":"dev-master",

    "ebizmarts/magemonkey" : "dev-master",

    "marko-m/inchoo_socialconnect":"dev-develop",
    "schumacherfm/opcache" : "dev-master",
    "pug-more/mageploy" : "dev-master",
    "fooman/emailattachments":"dev-master",
    "flagbit/magento-changeattributeset":"dev-master",
    "mage-eag/mage-enhanced-admin-grids":"*",
    "connect20/raveinfosys_deleteorder":"~1"
  },

  "require-dev": {
    "magento-ecg/coding-standard": "dev-master",
    "iwd/iwdopc" : "4.0.8" 
  },
}
```

Regards,
Valerio

**Comment by vmasciotta** [comment]
Ok, maybe I have good news.
@Santiagoebizmarts The problem looks disappeared after an update to the latest version.  I saw You made few modifications in the Observer.php on commit 42e3819c8976395f8c87695faeeda8624d610bc8 . Everything looks ok now. 
Anyway after a bit of debugging I noticed that https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Model/Observer.php#L427 there, You look for the "onestepcheckout" module name, but in Magento 1.9.* (I didn't check on older versions) module name is simply "checkout". This does not appear to create problems, but maybe it's worth checking.

@donalt can You update the module to the latest version, manually clean your cache folder, eventually unscribe from newsletter test users and check again? This are the steps I have done after the upgrade and, as I said, it seems to work.

**Comment by Santiagoebizmarts** [comment]
Hello,

That's great. I will add the checkout verification. Thanks for your feedback.
