### ISSUE TITLE
Choosing forgot password in Magento causes email confirmations to be sent

### ISSUE THREAD

**Issue by GavChap** [ebizmarts/magemonkey#95]
Magento: 1.14.2.1
Magemonkey: 1.1.35

Issue: 
When a user requests a new password, upon changing their password they will be sent a newsletter subscription confirmation email. This seems to be to do with the customer_save_after observer.

**Comment by Santiagoebizmarts** [comment]
Hello @GavChap,

Thanks for your feedback.
Do you have Magento's confirmation email or MailChimp's?
If you could show me a screenshot of your configuration (covering your API Key) would be grat.
This is working okay for me so I need to know exactly how you do this.

Regards.

**Comment by GavChap** [comment]
I will send one over tomorrow. We're using magento confirmation emails if
that helps.

On 3 Sep 2015 21:53, "Santiagoebizmarts" <notifications@github.com> wrote:
>
> Hello @GavChap,
>
> Thanks for your feedback.
> Do you have Magento's confirmation email or MailChimp's?
> If you could show me a screenshot of your configuration (covering your
API Key) would be grat.

**Comment by GavChap** [comment]
![configuration system magento admin](https://cloud.githubusercontent.com/assets/1280021/9679718/f21c0948-52e8-11e5-8133-d98040a3916d.png)

See attached

**Comment by GavChap** [comment]
More notes: I've managed to reproduce this using vanilla Magnento EE 1.14.2.1 and the current MageMonkey source. The only other extension I have installed is SMTP Pro to allow sending standard emails via Amazon SES. I've had to disable to the rewrite in Mandrill to get SMTP Pro to work.

**Comment by GavChap** [comment]
Hi, I saw that you'd updated the develop branch, so I tried downloading that branch and I still get the same issue of the newsletter subscription being sent whenever someone updates their account info. I'm using vanilla magento ee 1.14.2.1 and the development magento source, I've also removed SMTP Pro and used Mandrill to test if it's SMTP Pro causing the issue.

**Comment by gonzaloebiz** [comment]
Update to the current version 1.2.1, this is fixed
