### ISSUE TITLE
Allow subscribing to groups on customer account creation page

### ISSUE THREAD

**Issue by lfolco** [ebizmarts/magemonkey#98]
I noticed that this plugin explicitly denies the ability to subscribe to groups from the customer create page. Is there a reason for this? We used to add the checkboxes in the template and the backend would allow it; now there are a lot of checks that disallow this. I was wondering if there's an explicit reason for this.

**Comment by jaredkipe** [comment]
Please check out https://github.com/ebizmarts/magemonkey/pull/102

**Comment by gonzaloebiz** [comment]
Will be considered in the MageMonkey integration for Magento2
